import { ROLES } from "../lib/constants.js";

export const mockUsers = [
  {
    id: "u-reporter",
    name: "Asha Menon",
    email: "citizen@sahayog.in",
    password: "password",
    role: ROLES.REPORTER,
    status: "active",
    phone: "+91 98351 22345",
    org: "",
    district: "Ranchi",
    block: "Kanke",
    bio: "Civic community activist & volunteer in Ranchi district.",
  },
  {
    id: "u-govt",
    name: "Rajeshwar Soren",
    email: "panchayat@sahayog.in",
    password: "password",
    role: ROLES.GOVT_ORG,
    status: "active",
    phone: "+91 94312 88990",
    org: "Panchayat Samiti - Tamar",
    orgType: "Panchayat Samiti",
    district: "Ranchi",
    block: "Tamar",
    bio: "Block Development & Panchayat Executive Officer, Tamar Block.",
  },
  {
    id: "u-uni",
    name: "Dr. Kavita Rao",
    email: "university@sahayog.in",
    password: "password",
    role: ROLES.UNIVERSITY,
    status: "active",
    phone: "+91 94311 55678",
    org: "Birla Institute of Technology (BIT) Mesra",
    district: "Ranchi",
    block: "Kanke",
    disciplines: ["Environmental Science", "Civil Engineering", "Computer Science & IoT"],
    bio: "Head of Center for Rural Technology & Sustainability, BIT Mesra.",
  },
  {
    id: "u-uni-pending",
    name: "Prof. Imran Sheikh",
    email: "pendinguni@sahayog.in",
    password: "password",
    role: ROLES.UNIVERSITY,
    status: "pending",
    phone: "+91 91223 44556",
    org: "Kolhan University Chaibasa",
    district: "West Singhbhum (Chaibasa)",
    block: "Chaibasa",
    disciplines: ["Mining & Geological Sciences", "Agriculture & Rural Development"],
  },
  {
    id: "u-industry",
    name: "Rahul Desai",
    email: "industry@sahayog.in",
    password: "password",
    role: ROLES.INDUSTRY,
    status: "active",
    phone: "+91 98200 66789",
    org: "Tata Steel CSR & Sustainability",
    district: "East Singhbhum (Jamshedpur)",
    block: "Jamshedpur Urban",
    bio: "CSR Director managing Eastern Region community development initiatives.",
  },
  {
    id: "u-admin",
    name: "Meera Iyer",
    email: "admin@sahayog.in",
    password: "password",
    role: ROLES.ADMIN,
    status: "active",
    phone: "+91 651 244 5678",
    org: "Jharkhand State Innovation Council",
    district: "Ranchi",
    block: "Doranda",
    bio: "Chief Innovation Officer, Department of Higher & Technical Education.",
  },
];

const spark = (seed) =>
  Array.from({ length: 8 }, (_, i) => ({
    i,
    v: 12 + ((seed * (i + 3)) % 18) + i,
  }));

export const mockAnalytics = {
  stats: [
    { label: "Open issues", number: 142, badgeColor: "teal", trendData: spark(2), icon: "alert" },
    { label: "Universities active", number: 28, badgeColor: "blue", trendData: spark(5), icon: "university" },
    { label: "CSR Grants Deployed", number: "₹1.48 Cr", badgeColor: "amber", trendData: spark(8), icon: "industry" },
    { label: "Resolved & Verified", number: 58, badgeColor: "green", trendData: spark(3), icon: "check" },
  ],
  monthly: [
    { month: "Mar", reported: 42, resolved: 18 },
    { month: "Apr", reported: 51, resolved: 27 },
    { month: "May", reported: 47, resolved: 33 },
    { month: "Jun", reported: 63, resolved: 29 },
    { month: "Jul", reported: 58, resolved: 41 },
    { month: "Aug", reported: 71, resolved: 48 },
  ],
  categories: [
    { name: "Infrastructure", value: 38 },
    { name: "Water & Sanitation", value: 31 },
    { name: "Waste Management", value: 22 },
    { name: "Public Safety", value: 19 },
    { name: "Agriculture", value: 16 },
    { name: "Healthcare", value: 16 },
  ],
  csrBreakdown: [
    { sector: "Water & Sanitation", amount: 4850000, projects: 14 },
    { sector: "Infrastructure", amount: 4200000, projects: 12 },
    { sector: "Agriculture & Rural", amount: 2900000, projects: 8 },
    { sector: "Public Safety & Lighting", amount: 1850000, projects: 6 },
    { sector: "Waste Management", amount: 1000000, projects: 4 },
  ],
};

export const seedIssues = [
  {
    id: "iss-101",
    title: "Flooding and storm drain collapse at Albert Ekka Chowk",
    description: "During heavy monsoon rains, the main culvert collapses, causing waterlogging across 400m of commercial stretch and disabling traffic.",
    aiProblemStatement: "**Structured Problem Formulation:**\n\n**Context & Location:** Albert Ekka Chowk, Ranchi District (Urban Infrastructure).\n\n**Core Challenge:** Inadequate hydraulic capacity and sediment clogging in arterial storm drain cause severe urban inundation.\n\n**Severity Assessment:** High Priority (Score 88/100). Public Risk: 85%, Urgency: 90%.\n\n**Innovation Objective:** Design a prefabricated modular hydraulic bypass with smart debris filtration mesh.",
    category: "Infrastructure",
    status: "Resolved",
    priority: "High",
    upvotes: 46,
    upvoters: ["u-reporter", "u-uni", "u-industry"],
    reporterId: "u-reporter",
    reporterName: "Asha Menon",
    district: "Ranchi",
    block: "Town Area",
    landmark: "Near Albert Ekka Chowk Main Crossing",
    lat: 23.3700,
    lng: 85.3250,
    distanceKm: 8.5,
    createdAt: "2026-06-10T08:30:00.000Z",
    images: [
      { url: "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80", filename: "drain_inundation.jpg" }
    ],
    severity: { flooding: 92, publicRisk: 85, urgency: 90, score: 88 },
    assignee: "Birla Institute of Technology (BIT) Mesra",
    nearestUniversities: [
      { name: "Birla Institute of Technology (BIT) Mesra", distanceKm: 8.5, matchScore: 96 },
      { name: "Ranchi University", distanceKm: 4.2, matchScore: 91 },
    ],
    feedback: {
      rating: 5,
      comment: "The new modular drain grate and bypass fabricated by BIT Mesra completely eliminated waterlogging during yesterday's heavy storm!",
      verifiedByCitizen: true,
      submittedAt: "2026-08-18T14:20:00.000Z",
    },
    timeline: [
      { at: "2026-06-10T08:30:00.000Z", label: "Reported by Citizen with photo evidence" },
      { at: "2026-06-12T11:00:00.000Z", label: "AI synthesized formal engineering problem statement" },
      { at: "2026-06-15T14:30:00.000Z", label: "Claimed by BIT Mesra Civil & Mechanical team" },
      { at: "2026-06-25T16:00:00.000Z", label: "Funded (₹4,20,000) by Tata Steel CSR & Sustainability" },
      { at: "2026-08-15T12:00:00.000Z", label: "Ground installation & operational testing completed" },
      { at: "2026-08-18T14:20:00.000Z", label: "Citizen verified resolution & rated 5/5 stars ⭐" },
    ],
    comments: [
      {
        id: "c-1",
        authorId: "u-uni",
        authorName: "Dr. Kavita Rao",
        authorRole: "university",
        authorOrg: "BIT Mesra",
        text: "Our Civil Engineering student team visited the site yesterday. We have finalized hydraulic specs for the modular steel filter gate.",
        createdAt: "2026-06-18T10:15:00.000Z",
      },
      {
        id: "c-2",
        authorId: "u-industry",
        authorName: "Rahul Desai",
        authorRole: "industry",
        authorOrg: "Tata Steel CSR",
        text: "Tata Steel has released Tranche 1 (₹1,50,000) for procurement of corrosion-resistant structural steel.",
        createdAt: "2026-06-26T09:30:00.000Z",
      },
      {
        id: "c-3",
        authorId: "u-reporter",
        authorName: "Asha Menon",
        authorRole: "citizen",
        text: "Thank you team! Water flowed smoothly today even after 2 hours of non-stop monsoon rain.",
        createdAt: "2026-08-18T14:22:00.000Z",
      },
    ],
  },
  {
    id: "iss-102",
    title: "Fluoride and heavy metal contamination in rural borewell water",
    description: "Water testing across Tamar block revealed elevated fluoride levels (3.2 mg/L) and turbidity, causing dental fluorosis among school children.",
    aiProblemStatement: "**Structured Problem Formulation:**\n\n**Context & Location:** Tamar Block, Ranchi District (Water Resources & Public Health).\n\n**Core Issue:** Groundwater source exceeds permissible fluoride limits (3.2 mg/L), affecting 350+ tribal families.\n\n**Severity Assessment:** High Priority (Score 91/100). Urgency: 92%, Public Risk: 95%.\n\n**Innovation Objective:** Deploy an indigenous low-cost bio-char defluoridation filtration unit with continuous IoT turbidity telemetry.",
    category: "Water & Sanitation",
    status: "In progress",
    priority: "High",
    upvotes: 38,
    upvoters: ["u-reporter", "u-uni"],
    reporterId: "u-reporter",
    reporterName: "Asha Menon",
    district: "Ranchi",
    block: "Tamar",
    landmark: "Tamar Community Primary School Lane",
    lat: 23.052,
    lng: 85.648,
    distanceKm: 42.1,
    createdAt: "2026-07-29T06:45:00.000Z",
    images: [
      { url: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f7?auto=format&fit=crop&w=800&q=80", filename: "borewell_water.jpg" }
    ],
    severity: { flooding: 25, publicRisk: 95, urgency: 92, score: 91 },
    assignee: "Birla Institute of Technology (BIT) Mesra",
    nearestUniversities: [
      { name: "Birla Institute of Technology (BIT) Mesra", distanceKm: 42.1, matchScore: 94 },
      { name: "NIT Jamshedpur", distanceKm: 86.0, matchScore: 85 },
    ],
    timeline: [
      { at: "2026-07-29T06:45:00.000Z", label: "Reported by Citizen" },
      { at: "2026-08-01T10:00:00.000Z", label: "University multidisciplinary team formed by BIT Mesra" },
      { at: "2026-08-15T16:00:00.000Z", label: "Industry funding (₹3,50,000) approved by Tata Steel CSR (Deadline: Nov 30, 2026)" },
      { at: "2026-09-02T11:00:00.000Z", label: "Site survey & laboratory water sampling completed" },
    ],
    comments: [
      {
        id: "c-102-1",
        authorId: "u-uni",
        authorName: "Dr. Kavita Rao",
        authorRole: "university",
        authorOrg: "BIT Mesra",
        text: "Water samples from 3 community handpumps tested. Fluoride is 3.1 - 3.4 mg/L. Biochar absorption columns are being constructed in lab.",
        createdAt: "2026-08-20T11:30:00.000Z",
      },
      {
        id: "c-102-2",
        authorId: "u-industry",
        authorName: "Rahul Desai",
        authorRole: "industry",
        authorOrg: "Tata Steel CSR",
        text: "Tranche 1 (₹1,50,000) released. Please share baseline spectrophotometry reports when ready.",
        createdAt: "2026-08-22T14:10:00.000Z",
      },
    ],
  },
  {
    id: "iss-103",
    title: "Post-harvest vegetable cold storage failure in Mandar farm clusters",
    description: "Smallholder tomato & cauliflower farmers in Mandar face 35% post-harvest spoilage due to lack of localized grid-independent cooling storage.",
    aiProblemStatement: "**Structured Problem Formulation:**\n\n**Context & Location:** Mandar Block, Ranchi District (Agriculture & Rural Livelihoods).\n\n**Core Issue:** Lack of decentralized cold chains leads to distress sales and severe food wastage.\n\n**Severity Assessment:** Medium Priority (Score 68/100). Urgency: 65%, Public Risk: 70%.\n\n**Innovation Objective:** Develop a solar-powered evaporative passive cooling chamber built with locally sourced bamboo & clay.",
    category: "Agriculture",
    status: "Assigned",
    priority: "Medium",
    upvotes: 29,
    upvoters: ["u-reporter"],
    reporterId: "u-reporter",
    reporterName: "Asha Menon",
    district: "Ranchi",
    block: "Mandar",
    landmark: "Mandar Farmer Producer Organization Mandi",
    lat: 23.4610,
    lng: 85.0860,
    distanceKm: 28.0,
    createdAt: "2026-08-10T09:00:00.000Z",
    images: [],
    severity: { flooding: 15, publicRisk: 70, urgency: 65, score: 68 },
    assignee: "Birla Institute of Technology (BIT) Mesra",
    nearestUniversities: [
      { name: "Birla Institute of Technology (BIT) Mesra", distanceKm: 28.0, matchScore: 89 },
    ],
    timeline: [
      { at: "2026-08-10T09:00:00.000Z", label: "Reported by Citizen" },
      { at: "2026-08-14T11:00:00.000Z", label: "Claimed by BIT Mesra Agriculture & Mechanical team" },
    ],
    comments: [],
  },
  {
    id: "iss-104",
    title: "Unsafe dark road stretch near Chaibasa Tribal Girls Hostel",
    description: "1.2 km connecting road lacks street lighting and pedestrian footpaths, posing extreme safety hazards for 250+ students returning in evening.",
    aiProblemStatement: "**Structured Problem Formulation:**\n\n**Context & Location:** Chaibasa, West Singhbhum (Public Safety & Energy).\n\n**Core Issue:** Unlit peripheral road increases risk of accidents and vulnerability for female students.\n\n**Severity Assessment:** High Priority (Score 84/100). Urgency: 88%, Public Risk: 92%.\n\n**Innovation Objective:** Deploy intelligent motion-sensing standalone solar LED microgrids with panic alarm beacons.",
    category: "Public Safety",
    status: "New",
    priority: "High",
    upvotes: 52,
    upvoters: ["u-reporter", "u-uni-pending"],
    reporterId: "u-reporter",
    reporterName: "Asha Menon",
    district: "West Singhbhum (Chaibasa)",
    block: "Chaibasa Urban",
    landmark: "Opposite Tribal Welfare Girls Hostel",
    lat: 22.5604,
    lng: 85.8118,
    distanceKm: 110.0,
    createdAt: "2026-08-25T17:15:00.000Z",
    images: [],
    severity: { flooding: 10, publicRisk: 92, urgency: 88, score: 84 },
    assignee: null,
    nearestUniversities: [
      { name: "Kolhan University Chaibasa", distanceKm: 3.5, matchScore: 97 },
      { name: "NIT Jamshedpur", distanceKm: 65.0, matchScore: 88 },
    ],
    timeline: [
      { at: "2026-08-25T17:15:00.000Z", label: "Reported by Citizen" },
      { at: "2026-08-25T17:20:00.000Z", label: "AI synthesized problem statement & severity score (84/100)" },
    ],
    comments: [],
  },
  {
    id: "iss-105",
    title: "Industrial fly-ash dusting and air quality degradation in Dhanbad peri-urban belt",
    description: "Open coal and fly-ash transportation causes PM2.5 levels to breach 320 µg/m³, affecting school children and roadside vendors.",
    aiProblemStatement: "**Structured Problem Formulation:**\n\n**Context & Location:** Dhanbad District (Environment & Public Health).\n\n**Core Issue:** Particulate dust dispersion from uncovered transport corridors.\n\n**Severity Assessment:** High Priority (Score 86/100). Urgency: 84%, Public Risk: 89%.\n\n**Innovation Objective:** Deploy mist-cannon electrostatic precipitation barriers and real-time AQI warning sirens.",
    category: "Environment",
    status: "Under review",
    priority: "High",
    upvotes: 31,
    upvoters: ["u-reporter"],
    reporterId: "u-reporter",
    reporterName: "Asha Menon",
    district: "Dhanbad",
    block: "Jharia",
    landmark: "Jharia Bypass Road, Sector 3",
    lat: 23.7441,
    lng: 86.4130,
    distanceKm: 145.0,
    createdAt: "2026-08-28T10:00:00.000Z",
    images: [],
    severity: { flooding: 10, publicRisk: 89, urgency: 84, score: 86 },
    assignee: null,
    nearestUniversities: [
      { name: "IIT (ISM) Dhanbad", distanceKm: 6.2, matchScore: 98 },
    ],
    timeline: [
      { at: "2026-08-28T10:00:00.000Z", label: "Reported by Citizen" },
    ],
    comments: [],
  },
  {
    id: "iss-106",
    title: "Vaccine cold chain failure at Primary Health Centers across Tamar Block",
    description: "Frequent 8 to 12-hour rural power outages in Tamar Block disrupt vaccine refrigeration at 3 sub-health centers, jeopardizing critical infant immunization stocks and snakebite anti-venom vials.",
    aiProblemStatement: "**Structured Problem Formulation:**\n\n**Context & Location:** Tamar Block, Ranchi District (Healthcare & Renewable Energy Infrastructure).\n\n**Core Challenge:** Severe electrical grid intermittency and lack of thermal energy storage compromise vaccine cold chain integrity across 3 rural healthcare sub-centers.\n\n**Severity Assessment:** High Priority (Score 89/100). Urgency: 94%, Public Risk: 92%, Hazard Index: 15%.\n\n**Innovation Objective:** Develop and deploy an off-grid phase-change material (PCM) solar vaccine refrigerator equipped with automated GSM/IoT temperature telemetry.",
    category: "Healthcare",
    status: "Under review",
    priority: "High",
    upvotes: 41,
    upvoters: ["u-govt", "u-uni"],
    reporterId: "u-govt",
    reporterName: "Rajeshwar Soren",
    reporterRole: ROLES.GOVT_ORG,
    reporterOrg: "Panchayat Samiti - Tamar",
    district: "Ranchi",
    block: "Tamar",
    landmark: "Tamar Community Health Center & Salgadih Panchayat Bhawan",
    lat: 23.0515,
    lng: 85.6492,
    distanceKm: 43.5,
    createdAt: "2026-08-28T09:15:00.000Z",
    images: [
      { url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80", filename: "phc_cold_chain.jpg" }
    ],
    severity: { flooding: 10, publicRisk: 92, urgency: 94, score: 89 },
    assignee: null,
    nearestUniversities: [
      { name: "Birla Institute of Technology (BIT) Mesra", distanceKm: 43.5, matchScore: 95 },
      { name: "NIT Jamshedpur", distanceKm: 82.0, matchScore: 87 },
    ],
    timeline: [
      { at: "2026-08-28T09:15:00.000Z", label: "Reported by Local Govt Body (Panchayat Samiti - Tamar)" },
      { at: "2026-08-28T09:20:00.000Z", label: "AI synthesized cold chain formulation & risk matrix (Score 89/100)" },
      { at: "2026-08-29T10:00:00.000Z", label: "Dispatched to BIT Mesra Dept of Mechanical & Electrical Engineering" },
    ],
    comments: [
      {
        id: "c-106-1",
        authorId: "u-govt",
        authorName: "Rajeshwar Soren",
        authorRole: "govt_org",
        authorOrg: "Panchayat Samiti - Tamar",
        text: "We have designated the Tamar PHC backroom for prototype testing. Electricity is down 8-12 hours daily in monsoon season.",
        createdAt: "2026-08-28T10:00:00.000Z",
      },
    ],
  },
];

export const seedProjects = [
  {
    id: "prj-101",
    issueId: "iss-101",
    title: "Modular Hydraulic Grate & Urban Silt Bypass Unit",
    university: "Birla Institute of Technology (BIT) Mesra",
    industry: "Tata Steel CSR & Sustainability",
    status: "Completed",
    funded: true,
    fundingAmount: 420000,
    deadline: "2026-08-15",
    disbursedAmount: 420000,
    certificateStatus: "approved",
    certificateApprovedAt: "2026-08-19T10:00:00.000Z",
    certificateApprovedBy: "Jharkhand State Innovation Council Admin",
    certificateNotes: "Field implementation inspected and verified on ground with Ranchi Municipal Corporation.",
    tranches: [
      { tranche: 1, percent: 35, amount: 147000, released: true, releasedAt: "2026-06-26T09:30:00.000Z" },
      { tranche: 2, percent: 40, amount: 168000, released: true, releasedAt: "2026-07-20T11:00:00.000Z" },
      { tranche: 3, percent: 25, amount: 105000, released: true, releasedAt: "2026-08-15T15:00:00.000Z" },
    ],
    team: [
      { discipline: "Civil Engineering", members: ["Prof. S. K. Mahato", "Alok Ranjan", "Priya Verma"] },
      { discipline: "Mechanical Design", members: ["Rohan Gupta"] },
    ],
    proposal: "Manufacture corrosion-resistant high-throughput modular steel grates with vortex silt trap chambers to prevent drain clogging during peak monsoon runoffs.",
    milestones: [
      { name: "Hydraulic baseline & site topography survey", due: "2026-06-30", done: true, deliverableUrl: "https://example.com/survey_report.pdf" },
      { name: "Fabrication of 4 modular bypass steel units", due: "2026-07-20", done: true, deliverableUrl: "https://example.com/fabrication_test.pdf" },
      { name: "Ground civil installation & municipal handover", due: "2026-08-15", done: true, deliverableUrl: "https://example.com/handover_cert.pdf" },
    ],
  },
  {
    id: "prj-201",
    issueId: "iss-102",
    title: "Community Bio-char Defluoridation & IoT Sensor Network",
    university: "Birla Institute of Technology (BIT) Mesra",
    industry: "Tata Steel CSR & Sustainability",
    status: "Funded",
    funded: true,
    fundingAmount: 350000,
    deadline: "2026-11-30",
    disbursedAmount: 150000,
    certificateStatus: "none",
    tranches: [
      { tranche: 1, percent: 40, amount: 140000, released: true, releasedAt: "2026-08-22T14:10:00.000Z" },
      { tranche: 2, percent: 40, amount: 140000, released: false, releasedAt: null },
      { tranche: 3, percent: 20, amount: 70000, released: false, releasedAt: null },
    ],
    team: [
      { discipline: "Environmental Science", members: ["Dr. Kavita Rao", "Dev Prakash"] },
      { discipline: "Civil Engineering", members: ["Harsh Vardhan"] },
      { discipline: "Computer Science & IoT", members: ["Aman Singh"] },
    ],
    proposal: "Install a 500 LPH multi-stage gravity filtration plant with indigenous pyrolyzed biochar cartridges, coupled with continuous IoT fluoride telemetry dashboard.",
    milestones: [
      { name: "Site survey, chemical sampling & baseline spectrometry", due: "2026-09-15", done: true, deliverableUrl: "https://example.com/tamar_water_baseline.pdf" },
      { name: "Prototype filtration column fabrication & lab calibration", due: "2026-10-15", done: false, deliverableUrl: "" },
      { name: "Ground deployment, solar pump hookup & community telemetry handover", due: "2026-11-15", done: false, deliverableUrl: "" },
    ],
  },
  {
    id: "prj-103",
    issueId: "iss-103",
    title: "Decentralized Evaporative Passive Cold Storage Unit",
    university: "Birla Institute of Technology (BIT) Mesra",
    industry: "Tata Steel CSR & Sustainability",
    status: "Completed",
    funded: true,
    fundingAmount: 320000,
    deadline: "2026-08-30",
    disbursedAmount: 320000,
    certificateStatus: "pending_approval",
    tranches: [
      { tranche: 1, percent: 40, amount: 128000, released: true, releasedAt: "2026-07-05T10:00:00.000Z" },
      { tranche: 2, percent: 40, amount: 128000, released: true, releasedAt: "2026-07-28T14:00:00.000Z" },
      { tranche: 3, percent: 20, amount: 64000, released: true, releasedAt: "2026-08-30T16:00:00.000Z" },
    ],
    team: [
      { discipline: "Agriculture & Rural Development", members: ["Dr. S. Roy", "Anita Kumari"] },
      { discipline: "Mechanical Engineering", members: ["Kunal Sen"] },
    ],
    proposal: "Develop a decentralized solar-assisted zero-energy evaporative cooling chamber using local bamboo composite frames to protect perishable tomato and vegetable harvests.",
    milestones: [
      { name: "Thermal dynamics simulation & pilot chamber design", due: "2026-07-10", done: true, deliverableUrl: "https://example.com/cooling_design.pdf" },
      { name: "Installation at Mandar Farmer Producer Organization", due: "2026-08-05", done: true, deliverableUrl: "https://example.com/field_deployment.pdf" },
      { name: "Post-harvest shelf-life testing & FPO farmer training", due: "2026-08-30", done: true, deliverableUrl: "https://example.com/impact_assessment.pdf" },
    ],
  },
];
