import { create } from "zustand";

export const TRANSLATIONS = {
  en: {
    // TopBar & Header
    searchPlaceholder: "Search issues, research projects, universities, CSR partners...",
    liveNotifications: "Live Notifications",
    markAllRead: "Mark all read",
    noNotifications: "No new notifications.",
    viewProgressTracker: "View Progress Tracker →",
    signOut: "Sign out",
    language: "Language",
    signedInAs: "Signed in as",
    role: "Role",
    organization: "Organization",
    district: "District",
    
    // Roles
    citizen: "Citizen",
    govtOrg: "Govt / Local Body",
    govt_org: "Govt / Local Body",
    university: "University / HEI",
    industry: "Industry Partner",
    admin: "State Innovation Council (Admin)",

    // Navigation & Sidebar
    portalBrand: "Sahayog",
    portalSubtitle: "Societal Innovation Portal",
    navCitizenDashboard: "Dashboard",
    navMyIssues: "My Reports",
    navReportIssue: "Report Issue",
    navGisMap: "State Map",
    navShowcase: "Showcase",
    navHelpFaq: "Help",
    navUniDashboard: "Dashboard",
    navCampusQueue: "Local Issues",
    navProjects: "Projects",
    navCsrDashboard: "CSR Dashboard",
    navCsrQueue: "Proposals",
    navFundedProjects: "Funded",
    navAdminAnalytics: "Analytics",
    navVerifyAccounts: "Approvals",
    navAdminIssues: "Master Issue Console",
    navAdminAudit: "System Audit Logs",
    navWorkflow: "Workflow",
    workflowSubtitle: "Project-based collaboration notes between universities, industry, and government.",
    workflowNotes: "Workflow Notes",
    workflowCreateNote: "New Note",
    workflowEditNote: "Edit Note",
    workflowNoteTitle: "Note title",
    workflowNoteContent: "Workflow note content...",
    workflowSave: "Save Changes",
    workflowCreate: "Create Note",
    workflowCancel: "Cancel",
    workflowNoProjects: "No projects available",
    workflowNoProjectsHint: "Workflow notes are available once a university has claimed a project.",
    workflowNoNotes: "No workflow notes yet",
    workflowNoNotesHint: "University teams create notes to track their project execution.",
    workflowSelectNote: "Select a note on the left to view its full content.",
    workflowSuggestChange: "Suggest Change",
    workflowSuggestPlaceholder: "Describe the change you'd like to suggest...",
    workflowSubmitSuggestion: "Submit Suggestion",
    workflowSuggestions: "Business Suggestions",
    networkOverview: "Sahayog Network",
    networkActive: "Active",
    ctaReportCivic: "+ Report Civic Issue",
    ctaExploreQueue: "Explore Issue Queue",

    // Workflow Module
    workflowPageTitle: "Project Workflow",
    workflowPageSubtitle: "Track how universities progress through each problem statement and respond to CSR feedback.",
    workflowSelectProject: "Select a project to start",
    workflowSelectProjectHint: "Choose one of your projects below to view its workflow notes and suggestions.",
    workflowNoProjects: "No projects available for your account yet.",
    workflowNoProjectsHint: "Projects appear here once a university forms a team for a routed problem statement.",
    workflowNotesTab: "Workflow Notes",
    workflowSuggestionsTab: "Business Suggestions",
    workflowNewNote: "New Note",
    workflowEditNote: "Edit Note",
    workflowDeleteNote: "Delete Note",
    workflowNoteTitle: "Note title",
    workflowNoteTitlePlaceholder: "e.g. Implementation roadmap & site baseline",
    workflowNoteContent: "Note content",
    workflowNoteContentPlaceholder: "Describe the plan, technical decisions, progress and next steps for this project...",
    workflowSampleSuggestion: "Field progress updates geotagged for ESG reporting",
    workflowSaveNote: "Save Note",
    workflowSavingNote: "Saving...",
    workflowCancelEdit: "Cancel",
    workflowNoNotes: "No workflow notes yet.",
    workflowNoNotesHintUni: "Create the first note to document how your team is approaching this problem statement.",
    workflowNoNotesHintOther: "The owning university will share workflow notes here.",
    workflowSuggestChange: "Suggest Change",
    workflowSuggestionPlaceholder: "Describe the change or recommendation you want the university team to consider...",
    workflowSubmitSuggestion: "Submit Suggestion",
    workflowSubmitting: "Submitting...",
    workflowSuggestionStatus: "Status",
    workflowPending: "Pending",
    workflowReviewed: "Reviewed",
    workflowAccepted: "Accepted",
    workflowRejected: "Rejected",
    workflowMarkReviewed: "Mark Reviewed",
    workflowApprove: "Approve",
    workflowReject: "Reject",
    workflowNoSuggestions: "No business suggestions on this note yet.",
    workflowNoSuggestionsHintUni: "When CSR partners recommend changes, you can review, accept or reject them here.",
    workflowNoSuggestionsHintBiz: "Submit a suggestion to this note if you want the university team to consider a change.",
    workflowSuggestedBy: "Suggested by",
    workflowUpdatedAt: "Updated",
    workflowCreatedAt: "Created",
    workflowLoading: "Loading workflow...",
    workflowErrorLoad: "Could not load the workflow. Please try again.",
    workflowAccessDenied: "You do not have access to the Workflow area.",
    workflowNoteDeleted: "Workflow note deleted.",
    workflowNoteSaved: "Workflow note saved.",
    workflowSuggestionSent: "Suggestion submitted to the university team.",
    workflowStatusUpdated: "Suggestion status updated.",
    workflowBackToProjects: "Back to projects",
    workflowUniBadge: "University",
    workflowBizBadge: "CSR Partner",
    workflowAdminBadge: "Oversight",
    workflowViewOnly: "You are viewing this workflow in read-only mode.",
    workflowYouOwn: "You are the owning university for this project.",
    workflowYouSponsor: "You are the CSR partner for this project.",
    workflowCanvasTab: "Whiteboard",
    workflowObjects: "objects",
    workflowEmptyCanvas: "No canvas",
    workflowCanvasSaved: "Whiteboard saved.",
    wbSave: "Save Whiteboard",
    wbSaving: "Saving...",
    wbSaved: "Saved",
    wbUnsaved: "Unsaved changes",
    wbUndo: "Undo",
    wbClear: "Clear",
    wbViewOnly: "View only",
    wbViewOnlyHint: "This is a shared read-only view of the university's workflow whiteboard.",
    wbEmpty: "Your whiteboard is empty",
    wbEmptyHint: "Pick the pen, shapes or text tool above and start drawing the workflow.",
    wbEmptyView: "The workflow whiteboard is empty",
    wbEmptyViewHint: "The owning university has not drawn anything here yet.",
    wbTextPlaceholder: "Type text...",
    wbMoveTool: "Select / Move",
    wbMoveHint: "Tip: pick the Select tool, then drag any shape, arrow or freehand line to move it somewhere else.",

    // Design Thinking Board
    boardTitle: "Collaboration Board",
    boardBack: "Back to projects",
    execWorkflowTitle: "Execution Workflow",
    execWorkflowSubtitle: "Shared whiteboard — sketch implementation plans, timelines and responsibilities. The university can draw and edit; the business partner can view the changes live.",
    execWorkflowEditable: "Editable by the university",
    execWorkflowReadOnly: "View only for the business partner",
    execChecklistTitle: "Execution List — Resource Requisition Canvas",
    execChecklistSubtitle: "Every resource your project needs to move from plan to field, requested by the university and fulfilled by the business partner. Items stay pinned until the business marks them as provided.",
    execChecklistAdd: "Request Resource",
    execChecklistAddTitle: "Request a resource",
    execChecklistEditTitle: "Edit this requisition",
    execChecklistAddItem: "Add to List",
    execChecklistSave: "Save Changes",
    execChecklistSaving: "Saving…",
    execChecklistCancel: "Cancel",
    execChecklistItemPh: "What does the project need? e.g. 5000 L/day water filtration unit",
    execChecklistWhyPh: "Why do we need this? Explain how it unblocks execution…",
    execChecklistProgress: "Execution progress",
    execChecklistEmpty: "No resources requested yet",
    execChecklistEmptyUni: "Add the materials, equipment, and support your team needs to get the project into the field.",
    execChecklistEmptyBiz: "The university has not requested any resources yet. New requisitions will appear here for you to fulfill.",
    execChecklistWhy: "Why we need this:",
    execChecklistRequestedBy: "Requested by",
    execChecklistProvidedBy: "provided by",
    execChecklistProvide: "Provide this Resource",
    execChecklistProvided: "Provided",
    execChecklistEdit: "Edit",
    execChecklistDelete: "Delete",
    execChecklistDeleteConfirm: "Remove this requisition from the list?",
    boardDeniedHint: "The workflow board is private to the owning university team and their industry partners.",
    boardNewNote: "New Note",
    boardAddGuidance: "Add Guidance",
    boardAddNote: "Add Note",
    boardEditTitle: "Edit Note",
    boardEdit: "Edit",
    boardDelete: "Delete",
    boardDeleteConfirm: "Delete this note?",
    boardSave: "Save Changes",
    boardSaving: "Saving...",
    boardCancel: "Cancel",
    boardCreated: "Created",
    boardPickColumn: "Where should this note go?",
    boardPickHintUni: "Pick the Design Thinking phase you want to capture this note in.",
    boardPickHintBiz: "Add guidance or a request you want the university team to consider.",
    boardNoteTitle: "Short title (optional)",
    boardNoteContent: "Write your note... idea, feedback or data",
    boardGuidancePlaceholder: "Share guidance or a request with the university team...",
    boardCreateBizHint: "This will be tagged as Business guidance. The university team manages the board.",
    boardViewOnlyBiz: "View-only for CSR partners. You can add guidance notes, but only the university team can edit or move notes.",
    boardEditColumn: "Move to phase",
    boardAuthorUni: "University",
    boardAuthorBiz: "Business",
    boardEmptyHint: "No sticky notes yet.",
    boardEmptyClickHint: "Tap to add the first note",
    board_empathize: "Empathize",
    board_define: "Define",
    board_ideate: "Ideate",
    board_prototype: "Prototype",
    board_test: "Test",
    board_empathize_hint: "Understand users & context",
    board_define_hint: "Frame the core problem",
    board_ideate_hint: "Generate possibilities",
    board_prototype_hint: "Build a tangible model",
    board_test_hint: "Validate with reality",

    // Landing Page
    heroBadge: "AI-Powered Societal Innovation Platform",
    heroTitlePre: "Connecting Community Challenges with ",
    heroTitleHighlight: "Universities & Industry",
    heroSubtitle: "Citizens report grassroots civic issues with a brief summary & photo. Our AI Engine formulates structured problem statements and computes severity scores, auto-routing them to the nearest universities to form multidisciplinary research teams funded by industry partners with tracked milestones.",
    reportCivicBtn: "Report a Civic Issue",
    loginBtn: "University / Industry Login",
    adminLoginBtn: "Admin Login",
    signIn: "Sign in",
    joinNetwork: "Join Network",
    heroCheck1: "AI Problem Structuring",
    heroCheck2: "Proximity Haversine Routing",
    heroCheck3: "Real-time Citizen Notification",
    liveActivity: "Live Platform Activity",
    liveActivitySample: "Fluoride Defluoridation Pilot funded by Tata Steel CSR",
    liveActivitySampleSub: "Assigned to BIT Mesra · Nearest campus (12.4 km) · 60-day completion deadline",
    howItWorks: "How Sahayog Works",
    fromReportToResolution: "From Citizen Report to Ground Resolution",
    workflowStep1Title: "1. Citizen Reporting",
    workflowStep1Desc: "Citizens describe local issues with a brief summary, photo, and geolocation coordinates.",
    workflowStep2Title: "2. AI Formulation & Routing",
    workflowStep2Desc: "AI crafts a structured research problem statement, evaluates multi-factor severity, and routes to nearest universities.",
    workflowStep3Title: "3. University Solutions",
    workflowStep3Desc: "Faculty and students build multidisciplinary teams, design engineering prototypes, and submit solution proposals.",
    workflowStep4Title: "4. Industry Funding & Closure",
    workflowStep4Desc: "Industries sponsor proposals, set completion deadlines, track milestones, and the citizen is notified upon resolution.",
    platformImpactDashboard: "Platform Impact Dashboard",
    realtimeIndicators: "Real-time indicators across districts",
    viewFullAnalytics: "View full analytics →",
    copyrightFooter: "© 2026 Sahayog — Societal Innovation Collaboration Platform. All rights reserved.",
    collabCivicSolving: "Collaborative Civic Problem Solving",

    // Visual Workflow Notes Documentation (Landing)
    workflowDocTag: "Documentation",
    workflowDocTitle: "Visual Workflow Notes — Whiteboard Documentation",
    workflowDocSubtitle: "The complete specification of the whiteboard and suggestions workflow, shown directly on this page.",
    workflowDocLoading: "Loading documentation",
    workflowDocEmpty: "Documentation could not be loaded.",

    // Auth (Login & Signup)
    welcomeBack: "Welcome to Sahayog",
    signInWorkspace: "Sign in to your collaboration workspace.",
    continueGoogle: "Continue with Google",
    continueCredentials: "or continue with credentials",
    quickDemoSwitcher: "Quick Demo Account Switcher:",
    emailAddress: "Email address",
    password: "Password",
    signInToDashboard: "Sign in to Dashboard",
    signingIn: "Signing in...",
    newToSahayog: "New to Sahayog?",
    createAnAccount: "Create an account",
    alreadyHaveAccount: "Already have an account?",
    joinSahayogNetwork: "Join Sahayog Network",
    fullName: "Full Name",
    selectRole: "Select Your Role",
    institutionName: "University / Industry Name",
    department: "Department / CSR Wing",

    // Report Issue Wizard
    reportTitle: "Report a Civic Challenge",
    reportSubtitle: "Tell us the problem briefly with a photo. Our AI Engine formulates the research problem statement & severity for nearest universities.",
    stepBasic: "Basic Info",
    stepDesc: "Short Description",
    stepPhoto: "Photo Evidence",
    stepLocation: "Location",
    stepReview: "AI Formulation & Review",
    issueTitleLabel: "Short Issue Title",
    issueTitlePlaceholder: "e.g. Broken storm drain flooding Albert Ekka Chowk",
    categoryLabel: "Initial Category",
    selectCategory: "Select Domain Category",
    descLabel: "Brief Problem Description",
    descPlaceholder: "e.g. During monsoon, the drain overflows onto the main commercial stretch for over 300 meters...",
    descTip: "Tip: Keep it concise! Mention who is affected, key hazard details, and duration. The Sahayog AI model will automatically synthesize a formal, comprehensive problem statement for university researchers.",
    photoLabel: "Upload Photo / Evidence",
    photoSubtitle: "Visual evidence feeds the AI severity analysis to compute flooding risk, structural hazard, and urgency score.",
    districtLabel: "District (Jharkhand)",
    blockLabel: "Block / Municipality",
    blockPlaceholder: "e.g. Kanke / Tamar / Jamshedpur Urban",
    landmarkLabel: "Landmark / Street Address",
    landmarkPlaceholder: "e.g. Near Albert Ekka Chowk",
    pinLocationMap: "Pin Location on Map (For Nearest University Distance Calculation)",
    useGps: "Use current GPS location",
    aiSynthesizing: "Synthesizing AI problem statement...",
    aiFormulatedTitle: "AI-Formulated Problem Statement & Severity",
    regenerateAi: "Regenerate AI",
    publicRisk: "Public Risk",
    urgencyLevel: "Urgency Level",
    compositeScore: "Composite Score",
    backBtn: "Back",
    continueBtn: "Continue",
    submitBtn: "Submit to Nearest Universities",
    submittingBtn: "Publishing to Sahayog Network...",

    // My Reported Challenges
    myReportedChallenges: "My Reported Challenges",
    myReportedSubtitle: "Track problem evaluation, university team assignments, industry funding, and resolution milestones.",
    reportNewChallenge: "Report New Issue",
    noReportedIssues: "You have not reported any civic challenges yet.",
    noReportedHelper: "Report a local issue in your district with photo and location to activate AI problem formulation and route it to nearest universities.",

    // Issue Detail
    citizenDescription: "Citizen Description",
    aiSynthesizedTitle: "AI-Synthesized Problem Statement",
    evidencePhotos: "Photo Evidence & Uploads",
    nearestRoutingTitle: "Nearest Universities & Distance Routing",
    assembleTeamTitle: "Assemble Multidisciplinary Team",
    assembleTeamSubtitle: "Constitute student and faculty teams across disciplines to prepare the solution proposal.",
    saveTeamDraftProposal: "Save Team & Draft Proposal",
    exportCsrCert: "CSR Impact Certificate",
    claimChallenge: "Claim for University",
    claiming: "Claiming...",
    nearestCampus: "Nearest Campus",
    kmFromCampus: "km from campus",
    priority1: "Priority 1",
    priority2: "Priority 2",

    // Progress Tracker
    trackerTitle: "Live Ticket Progress Tracker",
    trackerSubtitle: "Real-time Amazon-style delivery tracker for citizen resolution",
    stageReported: "Reported & AI Assessed",
    stageAssigned: "University Team Formed",
    stageFunded: "Proposal & CSR Funded",
    stageExecution: "Field Execution & Milestones",
    stageResolved: "Resolved & Verified",
    stageCompleted: "Completed",
    stageInProgress: "In Progress",
    stageUpcoming: "Upcoming",
    liveActivityFeed: "Live Activity Stream & Milestone Audit Feed",
    overallResolution: "Overall Resolution",

    // Citizen Feedback & Verification
    feedbackTitle: "Citizen Resolution Verification & Rating",
    feedbackSubtitle: "Please verify on-ground satisfaction and rate the innovation team's solution.",
    rateSolution: "Rate the Quality & Speed of Resolution:",
    feedbackPlaceholder: "Tell the community and state innovation council about the impact (e.g. Water is clean and flowing now!)...",
    verifyGroundCheck: "I verify that this civic challenge has been physically resolved on the ground.",
    submitFeedbackBtn: "Submit Citizen Verification & Rating",
    verifiedByCitizenBadge: "Verified by Citizen Reporter",
    citizenRatingLabel: "Citizen Satisfaction Score",
    thankYouFeedback: "Thank you for verifying and rating this civic innovation project!",

    // University Pages
    uniDashboardTitle: "University Research & Innovation Hub",
    uniDashboardSubtitle: "Triage localized civic problems, assemble multidisciplinary student/faculty teams, and draft research proposals.",
    claimBtn: "Claim Challenge",
    claimedBadge: "Claimed by Campus",
    pendingProposals: "Proposals Awaiting CSR",
    activeProjectsCount: "Active Engineering Pilots",
    assignedQueueTitle: "Incoming Campus Triage Queue",

    // Industry Pages
    industryQueueTitle: "CSR Societal Innovation Queue",
    industryQueueSubtitle: "Review university research proposals, evaluate budget milestones, and allocate CSR grants for localized impact.",
    sponsorProposalBtn: "Sponsor & Fund Project",
    fundingAllocated: "Total CSR Grants Deployed",
    fundedProjectsTitle: "Industry Sponsored Projects",
    fundedProjectsSubtitle: "Monitor milestone deliverables, deadlines, and social impact of funded innovation projects.",

    // Industry Pages Additional
    csrEsgAnalytics: "Corporate CSR & ESG Analytics",
    csrEsgSubtitle: "Portfolio oversight of university-led societal innovation grants, escrow tranches, and verifiable ground impact.",
    reviewProposalsBtn: "Review Proposals",
    totalGrantsCommitted: "Total Grants Committed",
    activeSponsoredProjects: "Active Sponsored Projects",
    milestonesAchieved: "Milestones Achieved",
    disbursedViaEscrow: "Disbursed via Escrow",
    csrAllocationDomain: "CSR Allocation by Domain",
    csrScheduleSub: "Distribution across statutory CSR Schedule VII thematic heads",
    grantDisbursementVelocity: "Grant Disbursement Velocity",
    trancheReleasesSub: "Tranche releases based on verified milestones",
    activePortfolios: "Active Sponsored Project Portfolios",
    liveInnovationSub: "Live innovation pilots with milestone deliverables and escrow controls",
    manageAllFunded: "Manage All Funded Projects →",
    progress: "Progress",
    grant: "Grant",
    industrySponsoredProjects: "Industry Sponsored Projects",
    industrySponsoredSubtitle: "Monitor milestone deliverables, release milestone escrow tranches, and verify social impact.",
    milestoneUpdated: "Milestone updated.",
    partnerHeis: "Partner HEIs",
    sponsorship: "Sponsorship",
    leadUni: "Lead",
    targetDeadline: "Deadline",
    csrImpactCertBtn: "CSR Impact Certificate",
    milestoneCompletionVelocity: "Milestone Completion Velocity",
    deliverables: "Deliverables",
    csrEscrowSchedule: "CSR Escrow Tranche Disbursement Schedule",
    disbursed: "Disbursed",
    tranche: "Tranche",
    releaseTrancheBtn: "Release Tranche",
    milestoneDeliverablesHandover: "Milestone Deliverables & Ground Handover",
    target: "Target",
    viewReport: "View Report",
    noFundedProjectsYet: "No funded projects active yet. Go to Incoming Proposals to sponsor university solutions.",

    // Proposal Wizard
    formulateProposalTitle: "Formulate Solution Proposal",
    formulateProposalSubtitle: "Draft an engineering solution and milestones for submission to Industry / CSR funding partners.",
    stepScope: "Project Scope",
    stepTeam: "Multidisciplinary Team",
    stepNarrative: "Proposal Narrative",
    stepMilestones: "Milestones & Timeline",
    solutionTitleLabel: "Project / Solution Title",
    expectedImpactLabel: "Expected Community Impact",
    expectedImpactPlaceholder: "e.g. Eliminates waterlogging for 40,000+ daily commuters and reduces waterborne illnesses by 85%.",
    teamTitle: "Constitute Multidisciplinary Student & Faculty Team",
    teamSubtitle: "Bring together complementary disciplines (e.g. Civil Engineering + IoT/Computer Science + Environmental Science).",
    methodologyLabel: "Solution Technical Proposal & Methodology",
    milestonesTimelineLabel: "Milestones & Implementation Timelines",
    addMilestoneBtn: "+ Add another milestone",
    milestonePlaceholder: "Milestone Deliverable",
    submitToIndustryBtn: "Submit to Industry Partners",

    // Admin Pages
    adminDashboardTitle: "Statewide Innovation Command Center",
    adminDashboardSubtitle: "Real-time oversight of problem routing, HEI engagement, CSR grant allocation, and civic resolution velocity.",
    verifyAccountsTitle: "Institution & User Verification",
    verifyAccountsSubtitle: "Audit credentials and authorize Higher Education Institutions and Corporate CSR entities.",
    exportCsvAudit: "Export CSV Audit",
    printSummaryReport: "Print Summary Report",
    filterByDistrict: "Filter Overview by District:",
    allDistrictsConsolidated: "All 24 Jharkhand Districts (Consolidated)",
    reportedVsResolvedVelocity: "Reported vs. Resolved Challenges Velocity",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    accountVerificationsTab: "User & Institution Verifications",
    csrCertApprovalsTab: "CSR Certificate Approvals",
    certStatusCol: "Certificate Status",
    certPendingApproval: "Pending Admin Approval",
    certApproved: "Authorized / Approved",
    certRejected: "Revision Requested",
    approveCertBtn: "Approve Certificate",
    rejectCertBtn: "Request Revision",
    previewCertBtn: "Preview Certificate",
    downloadApprovedCertBtn: "Download Approved CSR Certificate",
    previewDraftCertBtn: "Preview Draft (Pending Approval)",
    certDraftWarning: "UNOFFICIAL DRAFT — PENDING STATE COUNCIL AUTHORIZATION",
    certDraftAlertDesc: "This project has concluded execution, but this certificate is not legally valid for corporate ESG tax filing or CSR credit until authorized by the State Oversight Admin.",
    certAdminApprovalSeal: "State Innovation Council Authorized Seal",
    certApprovedOn: "Authorized on",
    certSignedBy: "Authorized Signatory: State Innovation Council Admin",
    noPendingCerts: "No CSR certificates currently awaiting administrative approval.",

    // Showcase & Help & Citizen & Map
    showcaseHeroBadge: "Societal Innovation Impact Showcase",
    showcaseHeroTitle: "Grassroots Problems Solved by Campus Research & CSR",
    showcaseHeroSubtitle: "Explore verifiable engineering solutions, low-cost prototypes, and community deployments developed by student-faculty teams and funded by corporate CSR partners across Jharkhand.",
    allShowcases: "All Showcases",
    helpCenterBadge: "Help Center & Knowledgebase",
    helpCenterTitle: "Frequently Asked Questions & Support",
    helpCenterSubtitle: "Learn how Sahayog connects grassroots civic challenges with university R&D teams and corporate CSR funding.",
    submitInquiryTitle: "Submit a Support Inquiry",
    subjectLabel: "Subject / Topic",
    categoryGeneral: "General Inquiries",
    categoryTechnical: "Technical / Platform Issues",
    categoryFunding: "CSR Funding & Escrow",
    inquiryMessageLabel: "Detailed Message",
    submitInquiryBtn: "Submit Inquiry",
    submittingInquiry: "Sending inquiry...",
    citizenDashboardTitle: "Citizen Impact Dashboard",
    activeReporterBadge: "Active Reporter",
    citizenWelcomePre: "Welcome back,",
    citizenWelcomeSub: "Track your civic problem submissions, local community upvotes, and university solutions.",
    exploreMapBtn: "Explore Map",
    totalReportedCount: "Total Reported",
    nearbyChallengesTitle: "Nearby Community Challenges",
    upvote: "Upvote",
    upvoted: "Upvoted",
    gisMapTitle: "Statewide GIS Innovation Map",
    gisMapSubtitle: "Real-time geospatial visualization of civic challenges, HEI proximity radii, and CSR-funded deployments across Jharkhand.",
    legendUrgent: "High/Urgent",
    legendAssigned: "Campus Assigned",
    legendResolved: "Resolved",
    allDistrictsCount: "All 24 Districts",
    autoRoutedCampus: "Auto-routed based on proximity to campus",

    // Status Badges
    statusNew: "New",
    statusUnderReview: "Under review",
    statusAssigned: "Assigned",
    statusInProgress: "In progress",
    statusFunded: "Funded",
    statusResolved: "Resolved",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
  },

  hi: {
    // TopBar & Header
    searchPlaceholder: "समस्याएं, शोध परियोजनाएं, विश्वविद्यालय, सीएसआर भागीदार खोजें...",
    liveNotifications: "ताज़ा सूचनाएं",
    markAllRead: "सभी पढ़ी गई चिह्नित करें",
    noNotifications: "कोई नई सूचना नहीं।",
    viewProgressTracker: "प्रगति ट्रैकर देखें →",
    signOut: "लॉग आउट करें",
    language: "भाषा",
    signedInAs: "लॉग इन उपयोगकर्ता",
    role: "भूमिका",
    organization: "संस्थान / संगठन",
    district: "जिला",

    // Roles
    citizen: "नागरिक",
    govtOrg: "सरकारी / स्थानीय निकाय",
    govt_org: "सरकारी / स्थानीय निकाय",
    university: "विश्वविद्यालय / संस्थान",
    industry: "उद्योग / CSR भागीदार",
    admin: "राज्य नवाचार परिषद (प्रशासन)",

    // Navigation & Sidebar
    portalBrand: "सहयोग",
    portalSubtitle: "सामाजिक नवाचार पोर्टल",
    navCitizenDashboard: "डैशबोर्ड",
    navMyIssues: "मेरी रिपोर्ट",
    navReportIssue: "समस्या दर्ज करें",
    navGisMap: "राज्य नक्शा",
    navShowcase: "शोकेस",
    navHelpFaq: "सहायता",
    navUniDashboard: "डैशबोर्ड",
    navCampusQueue: "स्थानीय समस्याएं",
    navProjects: "परियोजनाएं",
    navCsrDashboard: "CSR डैशबोर्ड",
    navCsrQueue: "प्रस्ताव",
    navFundedProjects: "स्वीकृत",
    navAdminAnalytics: "विश्लेषण",
    navVerifyAccounts: "अनुमोदन",
    navAdminIssues: "मास्टर समस्या कंसोल",
    navAdminAudit: "सिस्टम ऑडिट लॉग्स",
    navWorkflow: "वर्कफ़्लो",
    workflowSubtitle: "विश्वविद्यालय, उद्योग और सरकार के बीच परियोजना सहयोग संबंधी नोट्स।",
    workflowNotes: "वर्कफ़्लो नोट्स",
    workflowCreateNote: "नया नोट",
    workflowEditNote: "नोट संपादित करें",
    workflowNoteTitle: "नोट का शीर्षक",
    workflowNoteContent: "वर्कफ़्लो नोट सामग्री...",
    workflowSave: "बदलाव सेव करें",
    workflowCreate: "नोट बनाएं",
    workflowCancel: "रद्द करें",
    workflowNoProjects: "कोई परियोजना उपलब्ध नहीं",
    workflowNoProjectsHint: "विश्वविद्यालय द्वारा परियोजना दावा करने के बाद वर्कफ़्लो नोट्स उपलब्ध होंगे।",
    workflowNoNotes: "अभी तक कोई वर्कफ़्लो नोट नहीं",
    workflowNoNotesHint: "विश्वविद्यालय टीमें अपनी परियोजना की प्रगति ट्रैक करने के लिए नोट्स बनाती हैं।",
    workflowSelectNote: "पूरी सामग्री देखने के लिए बाईं ओर का नोट चुनें।",
    workflowSuggestChange: "बदलाव सुझाएं",
    workflowSuggestPlaceholder: "आपके द्वारा सुझाया गया बदलाव लिखें...",
    workflowSubmitSuggestion: "सुझाव भेजें",
    workflowSuggestions: "व्यावसायिक सुझाव",
    networkOverview: "सहयोग नेटवर्क",
    networkActive: "सक्रिय",
    ctaReportCivic: "+ नागरिक समस्या दर्ज करें",
    ctaExploreQueue: "समस्या कतार देखें",

    // Workflow Module
    workflowPageTitle: "परियोजना वर्कफ़्लो",
    workflowPageSubtitle: "देखें कि विश्वविद्यालय प्रत्येक समस्या विवरण पर कैसे आगे बढ़ रहा है और CSR फीडबैक पर कैसे प्रतिक्रिया दे रहा है।",
    workflowSelectProject: "शुरू करने के लिए एक परियोजना चुनें",
    workflowSelectProjectHint: "नीचे अपनी किसी एक परियोजना को चुनकर उसके वर्कफ़्लो नोट और सुझाव देखें।",
    workflowNoProjects: "आपके खाते के लिए अभी कोई परियोजना उपलब्ध नहीं है।",
    workflowNoProjectsHint: "जब विश्वविद्यालय किसी रूट की गई समस्या के लिए टीम बनाता है तो परियोजनाएं यहां दिखती हैं।",
    workflowNotesTab: "वर्कफ़्लो नोट",
    workflowSuggestionsTab: "व्यापार सुझाव",
    workflowNewNote: "नया नोट",
    workflowEditNote: "नोट संपादित करें",
    workflowDeleteNote: "नोट हटाएं",
    workflowNoteTitle: "नोट का शीर्षक",
    workflowNoteTitlePlaceholder: "उदा. कार्यान्वयन रोडमैप और साइट बेसलाइन",
    workflowNoteContent: "नोट की सामग्री",
    workflowNoteContentPlaceholder: "इस परियोजना की योजना, तकनीकी निर्णय, प्रगति और अगले चरण लिखें...",
    workflowSampleSuggestion: "ESG रिपोर्टिंग के लिए जियोटैग किए गए प्रगति अपडेट",
    workflowSaveNote: "नोट सहेजें",
    workflowSavingNote: "सहेजा जा रहा है...",
    workflowCancelEdit: "रद्द करें",
    workflowNoNotes: "अभी कोई वर्कफ़्लो नोट नहीं है।",
    workflowNoNotesHintUni: "टीम इस समस्या विवरण से कैसे निपट रही है, इसका पहला नोट बनाएं।",
    workflowNoNotesHintOther: "स्वामी विश्वविद्यालय वर्कफ़्लो नोट यहां साझा करेगा।",
    workflowSuggestChange: "परिवर्तन सुझाएं",
    workflowSuggestionPlaceholder: "वह परिवर्तन या सिफारिश बताएं जो आप विश्वविद्यालय टीम से विचार कराना चाहते हैं...",
    workflowSubmitSuggestion: "सुझाव जमा करें",
    workflowSubmitting: "जमा हो रहा है...",
    workflowSuggestionStatus: "स्थिति",
    workflowPending: "लंबित",
    workflowReviewed: "समीक्षित",
    workflowAccepted: "स्वीकृत",
    workflowRejected: "अस्वीकृत",
    workflowMarkReviewed: "समीक्षित करें",
    workflowApprove: "स्वीकृत करें",
    workflowReject: "अस्वीकृत करें",
    workflowNoSuggestions: "इस नोट पर अभी कोई व्यापार सुझाव नहीं है।",
    workflowNoSuggestionsHintUni: "जब CSR साझेदार बदलाव की सलाह देते हैं तो आप यहां समीक्षा, स्वीकृति या अस्वीकृति कर सकते हैं।",
    workflowNoSuggestionsHintBiz: "यदि आप चाहते हैं कि विश्वविद्यालय टीम किसी बदलाव पर विचार करे तो इस नोट पर सुझाव भेजें।",
    workflowSuggestedBy: "सुझाव दिया",
    workflowUpdatedAt: "अपडेट",
    workflowCreatedAt: "बनाया गया",
    workflowLoading: "वर्कफ़्लो लोड हो रहा है...",
    workflowErrorLoad: "वर्कफ़्लो लोड नहीं हो सका। कृपया पुनः प्रयास करें।",
    workflowAccessDenied: "आपको वर्कफ़्लो क्षेत्र तक पहुंच की अनुमति नहीं है।",
    workflowNoteDeleted: "वर्कफ़्लो नोट हटा दिया गया।",
    workflowNoteSaved: "वर्कफ़्लो नोट सहेज लिया गया।",
    workflowSuggestionSent: "सुझाव विश्वविद्यालय टीम को भेज दिया गया।",
    workflowStatusUpdated: "सुझाव की स्थिति अपडेट हो गई।",
    workflowBackToProjects: "परियोजनाओं पर वापस जाएं",
    workflowUniBadge: "विश्वविद्यालय",
    workflowBizBadge: "CSR साझेदार",
    workflowAdminBadge: "निगरानी",
    workflowViewOnly: "आप इस वर्कफ़्लो को केवल पढ़ने मोड में देख रहे हैं।",
    workflowYouOwn: "आप इस परियोजना के स्वामी विश्वविद्यालय हैं।",
    workflowYouSponsor: "आप इस परियोजना के CSRसाझेदार हैं।",
    workflowCanvasTab: "व्हाइटबोर्ड",
    workflowObjects: "ऑब्जेक्ट",
    workflowEmptyCanvas: "कोई कैनवास नहीं",
    workflowCanvasSaved: "व्हाइटबोर्ड सहेज लिया गया।",
    wbSave: "व्हाइटबोर्ड सहेजें",
    wbSaving: "सहेजा जा रहा है...",
    wbSaved: "सहेजा गया",
    wbUnsaved: "असहेजे बदलाव",
    wbUndo: "वापस करें",
    wbClear: "साफ़ करें",
    wbViewOnly: "केवल देखें",
    wbViewOnlyHint: "यह विश्वविद्यालय के वर्कफ़्लो व्हाइटबोर्ड का साझा रीड-ओनली दृश्य है।",
    wbEmpty: "आपका व्हाइटबोर्ड खाली है",
    wbEmptyHint: "ऊपर से पेन, आकृति या टेक्स्ट टूल चुनें और वर्कफ़्लो बनाना शुरू करें।",
    wbEmptyView: "वर्कफ़्लो व्हाइटबोर्ड खाली है",
    wbEmptyViewHint: "स्वामी विश्वविद्यालय ने अभी यहां कुछ नहीं बनाया है।",
    wbTextPlaceholder: "टेक्स्ट लिखें...",
    wbMoveTool: "चुनें / स्थान बदलें",
    wbMoveHint: "सलाह: Select टूल चुनें, फिर किसी भी आकृति, तीर या फ्रीहैंड लाइन को खींचकर कहीं और ले जाएं।",

    // Design Thinking Board
    boardTitle: "सहयोग बोर्ड",
    boardBack: "परियोजनाओं पर वापस",
    execWorkflowTitle: "कार्यान्वयन कार्यप्रवाह",
    execWorkflowSubtitle: "साझा व्हाइटबोर्ड — कार्यान्वयन योजनाएं, समयरेखा और ज़िम्मेदारियां बनाएं। विश्वविद्यालय लिख और संपादित कर सकता है; व्यापार साझेदार परिवर्तन लाइव देख सकता है।",
    execWorkflowEditable: "विश्वविद्यालय के लिए संपादन योग्य",
    execWorkflowReadOnly: "व्यापार साझेदार के लिए केवल देखने योग्य",
    execChecklistTitle: "निष्पादन सूची — संसाधन आवश्यकता कैनवास",
    execChecklistSubtitle: "आपके प्रोजेक्ट को योजना से मैदान तक ले जाने के लिए ज़रूरी हर संसाधन, जिसे विश्वविद्यालय अनुरोध करता है और व्यापार साझेदार पूरा करता है। जब तक व्यापार उसे प्रदान नहीं करता, आइटम सूची में बना रहता है।",
    execChecklistAdd: "संसाधन अनुरोध करें",
    execChecklistAddTitle: "संसाधन का अनुरोध करें",
    execChecklistEditTitle: "इस अनुरोध को संपादित करें",
    execChecklistAddItem: "सूची में जोड़ें",
    execChecklistSave: "बदलाव सहेजें",
    execChecklistSaving: "सहेजा जा रहा है…",
    execChecklistCancel: "रद्द करें",
    execChecklistItemPh: "प्रोजेक्ट को क्या चाहिए? जैसे 5000 लीटर/दिन जल शोधन इकाई",
    execChecklistWhyPh: "हमें इसकी आवश्यकता क्यों है? बताएं कि यह कार्यान्वयन में कैसे मदद करेगा…",
    execChecklistProgress: "निष्पादन प्रगति",
    execChecklistEmpty: "अभी कोई संसाधन अनुरोध नहीं",
    execChecklistEmptyUni: "उन सामग्रियों, उपकरणों और सहायता को जोड़ें जिनकी आपकी टीम को प्रोजेक्ट को मैदान तक ले जाने के लिए आवश्यकता है।",
    execChecklistEmptyBiz: "विश्वविद्यालय ने अभी कोई संसाधन अनुरोध नहीं किया है। नए अनुरोध यहां दिखेंगे।",
    execChecklistWhy: "हमें इसकी आवश्यकता क्यों है:",
    execChecklistRequestedBy: "अनुरोधकर्ता",
    execChecklistProvidedBy: "द्वारा प्रदान",
    execChecklistProvide: "यह संसाधन प्रदान करें",
    execChecklistProvided: "प्रदान किया गया",
    execChecklistEdit: "संपादित करें",
    execChecklistDelete: "हटाएं",
    execChecklistDeleteConfirm: "इस अनुरोध को सूची से हटाएं?",
    boardDeniedHint: "वर्कफ़्लो बोर्ड केवल संबंधित विश्वविद्यालय टीम और उनके उद्योग भागीदारों के लिए निजी है।",
    boardNewNote: "नया नोट",
    boardAddGuidance: "मार्गदर्शन जोड़ें",
    boardAddNote: "नोट जोड़ें",
    boardEditTitle: "नोट संपादित करें",
    boardEdit: "संपादित करें",
    boardDelete: "हटाएं",
    boardDeleteConfirm: "इस नोट को हटाएं?",
    boardSave: "बदलाव सहेजें",
    boardSaving: "सहेजा जा रहा है...",
    boardCancel: "रद्द करें",
    boardCreated: "बनाया गया",
    boardPickColumn: "यह नोट कहाँ जाना चाहिए?",
    boardPickHintUni: "वह डिज़ाइन थिंकिंग चरण चुनें जिसमें आप यह नोट जोड़ना चाहते हैं।",
    boardPickHintBiz: "अपना मार्गदर्शन या अनुरोध जोड़ें, जिस पर विश्वविद्यालय टीम विचार करे।",
    boardNoteTitle: "छोटा शीर्षक (वैकल्पिक)",
    boardNoteContent: "अपना नोट लिखें... विचार, प्रतिक्रिया या डेटा",
    boardGuidancePlaceholder: "विश्वविद्यालय टीम के साथ मार्गदर्शन या अनुरोध साझा करें...",
    boardCreateBizHint: "इसे Business मार्गदर्शन के रूप में चिह्नित किया जाएगा। बोर्ड का प्रबंधन विश्वविद्यालय टीम करती है।",
    boardViewOnlyBiz: "CSR भागीदारों के लिए केवल-दृश्य। आप मार्गदर्शन नोट जोड़ सकते हैं, पर केवल विश्वविद्यालय टीम नोट संपादित या स्थानांतरित कर सकती है।",
    boardEditColumn: "चरण में ले जाएं",
    boardAuthorUni: "विश्वविद्यालय",
    boardAuthorBiz: "Business",
    boardEmptyHint: "अभी तक कोई स्टिकी नोट नहीं।",
    boardEmptyClickHint: "पहला नोट जोड़ने के लिए क्लिक करें",
    board_empathize: "सहानुभूति",
    board_define: "परिभाषित करें",
    board_ideate: "विचार करें",
    board_prototype: "प्रोटोटाइप",
    board_test: "परीक्षण",
    board_empathize_hint: "उपयोगकर्ताओं और संदर्भ को समझें",
    board_define_hint: "मुख्य समस्या निर्धारित करें",
    board_ideate_hint: "संभावनाएं उत्पन्न करें",
    board_prototype_hint: "ठोस मॉडल बनाएं",
    board_test_hint: "वास्तविकता से सत्यापित करें",

    // Landing Page
    heroBadge: "AI-संचालित सामाजिक नवाचार मंच",
    heroTitlePre: "नागरिक समस्याओं को जोड़ना ",
    heroTitleHighlight: "विश्वविद्यालयों और उद्योग जगत से",
    heroSubtitle: "नागरिक फोटो और संक्षिप्त विवरण के साथ जमीनी समस्याएं दर्ज करते हैं। हमारा AI इंजन औपचारिक शोध समस्या विवरण तैयार कर नजदीकी विश्वविद्यालयों को भेजता है, जहां बहुविषयक टीमें उद्योग सीएसआर फंडिंग से समाधान बनाती हैं।",
    reportCivicBtn: "नागरिक समस्या दर्ज करें",
    loginBtn: "विश्वविद्यालय / उद्योग लॉगिन",
    adminLoginBtn: "प्रशासक लॉगिन",
    signIn: "लॉगिन करें",
    joinNetwork: "नेटवर्क से जुड़ें",
    heroCheck1: "AI समस्या सूत्रीकरण",
    heroCheck2: "निकटतम विश्वविद्यालय रूटिंग",
    heroCheck3: "नागरिकों को रीयल-टाइम सूचना",
    liveActivity: "मंच की लाइव गतिविधि",
    liveActivitySample: "टाटा स्टील सीएसआर द्वारा वित्तपोषित फ्लोराइड शुद्धिकरण पायलट",
    liveActivitySampleSub: "बीआईटी मेसरा को आवंटित · निकटतम परिसर (12.4 किमी) · 60 दिन की समयसीमा",
    howItWorks: "सहयोग कैसे काम करता है",
    fromReportToResolution: "नागरिक रिपोर्ट से लेकर जमीनी समाधान तक",
    workflowStep1Title: "1. नागरिक रिपोर्टिंग",
    workflowStep1Desc: "नागरिक संक्षिप्त विवरण, फोटो और स्थान के साथ स्थानीय समस्या दर्ज करते हैं।",
    workflowStep2Title: "2. AI विश्लेषण और रूटिंग",
    workflowStep2Desc: "AI औपचारिक समस्या विवरण तैयार कर गंभीरता आंकता है और नजदीकी विश्वविद्यालयों को भेजता है।",
    workflowStep3Title: "3. विश्वविद्यालय समाधान",
    workflowStep3Desc: "प्रोफेसर और छात्र बहुविषयक टीमें बनाकर प्रोटोटाइप तैयार करते हैं और प्रस्ताव भेजते हैं।",
    workflowStep4Title: "4. उद्योग फंडिंग और समाधान",
    workflowStep4Desc: "उद्योग CSR से अनुदान देते हैं, माइलस्टोन ट्रैक करते हैं और समाधान होने पर नागरिक को सूचना मिलती है।",
    platformImpactDashboard: "मंच प्रभाव डैशबोर्ड",
    realtimeIndicators: "जिलों में रीयल-टाइम आंकड़े",
    viewFullAnalytics: "पूर्ण विश्लेषण देखें →",
    copyrightFooter: "© 2026 सहयोग — सामाजिक नवाचार सहभागिता मंच। सर्वाधिकार सुरक्षित।",
    collabCivicSolving: "सहयोगात्मक नागरिक समस्या समाधान",

    // Auth (Login & Signup)
    welcomeBack: "सहयोग में आपका स्वागत है",
    signInWorkspace: "अपने सहभागिता डैशबोर्ड में लॉगिन करें।",
    continueGoogle: "Google के साथ जारी रखें",
    continueCredentials: "या ईमेल और पासवर्ड से जारी रखें",
    quickDemoSwitcher: "त्वरित डेमो खाता चयनकर्ता:",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    signInToDashboard: "डैशबोर्ड में लॉगिन करें",
    signingIn: "लॉगिन हो रहा है...",
    newToSahayog: "सहयोग पर नए हैं?",
    createAnAccount: "नया खाता बनाएं",
    alreadyHaveAccount: "क्या आपके पास पहले से खाता है?",
    joinSahayogNetwork: "सहयोग नेटवर्क से जुड़ें",
    fullName: "पूरा नाम",
    selectRole: "अपनी भूमिका चुनें",
    institutionName: "विश्वविद्यालय / उद्योग का नाम",
    department: "विभाग / सीएसआर शाखा",

    // Report Issue Wizard
    reportTitle: "नागरिक समस्या दर्ज करें",
    reportSubtitle: "फोटो और संक्षिप्त विवरण दें। हमारा AI इंजन समस्या का शोध विवरण तैयार कर नजदीकी विश्वविद्यालय को भेजेगा।",
    stepBasic: "मूल जानकारी",
    stepDesc: "समस्या विवरण",
    stepPhoto: "फोटो प्रमाण",
    stepLocation: "स्थान",
    stepReview: "AI विश्लेषण और समीक्षा",
    issueTitleLabel: "समस्या का शीर्षक",
    issueTitlePlaceholder: "उदा. अल्बर्ट एक्का चौक पर जलभराव और नाली जाम",
    categoryLabel: "समस्या की श्रेणी",
    selectCategory: "श्रेणी चुनें",
    descLabel: "समस्या का संक्षिप्त विवरण",
    descPlaceholder: "उदा. बारिश में नाला सड़क पर बहने लगता है, जिससे 300 मीटर तक आवागमन बंद हो जाता है...",
    descTip: "सुझाव: विवरण संक्षिप्त रखें! प्रभावित लोगों, मुख्य खतरे और अवधि का उल्लेख करें। सहयोग AI मॉडल शोधकर्ताओं के लिए औपचारिक समस्या विवरण तैयार करेगा।",
    photoLabel: "फोटो / प्रमाण अपलोड करें",
    photoSubtitle: "फोटो से AI बाढ़ जोखिम, सुरक्षा खतरा और तात्कालिकता स्कोर की गणना करता है।",
    districtLabel: "जिला (झारखंड)",
    blockLabel: "प्रखंड / नगर निकाय",
    blockPlaceholder: "उदा. कांके / तमाड़ / जमशेदपुर",
    landmarkLabel: "लैंडमार्क / सड़क का नाम",
    landmarkPlaceholder: "उदा. अल्बर्ट एक्का चौक के पास",
    pinLocationMap: "नक्शे पर सटीक स्थान चुनें (विश्वविद्यालय दूरी गणना हेतु)",
    useGps: "वर्तमान GPS स्थान का उपयोग करें",
    aiSynthesizing: "AI शोध विवरण तैयार किया जा रहा है...",
    aiFormulatedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या और गंभीरता",
    regenerateAi: "पुनः AI बनाएं",
    publicRisk: "सार्वजनिक जोखिम",
    urgencyLevel: "तात्कालिकता",
    compositeScore: "कुल गंभीरता स्कोर",
    backBtn: "पीछे",
    continueBtn: "आगे बढ़ें",
    submitBtn: "नजदीकी विश्वविद्यालयों को भेजें",
    submittingBtn: "सहयोग नेटवर्क पर प्रकाशित हो रहा है...",

    // My Reported Challenges
    myReportedChallenges: "मेरी दर्ज की गई समस्याएं",
    myReportedSubtitle: "समस्या मूल्यांकन, विश्वविद्यालय टीम गठन, उद्योग फंडिंग और समाधान माइलस्टोन को ट्रैक करें।",
    reportNewChallenge: "नई समस्या दर्ज करें",
    noReportedIssues: "आपने अभी तक कोई नागरिक समस्या दर्ज नहीं की है।",
    noReportedHelper: "AI विश्लेषण शुरू करने और नजदीकी विश्वविद्यालयों तक पहुंचाने के लिए अपने जिले की समस्या फोटो सहित दर्ज करें।",

    // Issue Detail
    citizenDescription: "नागरिक द्वारा दिया गया विवरण",
    aiSynthesizedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या",
    evidencePhotos: "फोटो प्रमाण व अपलोड",
    nearestRoutingTitle: "नजदीकी विश्वविद्यालय और दूरी रूटिंग",
    assembleTeamTitle: "बहुविषयक अनुसंधान टीम गठित करें",
    assembleTeamSubtitle: "समाधान प्रस्ताव तैयार करने के लिए विभिन्न विभागों के छात्रों और प्रोफेसरों की टीम बनाएं।",
    saveTeamDraftProposal: "टीम सुरक्षित करें और प्रस्ताव बनाएं",
    exportCsrCert: "CSR इम्पैक्ट प्रमाणपत्र",
    claimChallenge: "विश्वविद्यालय के लिए दावा करें",
    claiming: "दावा दर्ज हो रहा है...",
    nearestCampus: "निकटतम परिसर",
    kmFromCampus: "किमी परिसर से दूर",
    priority1: "प्राथमिकता 1",
    priority2: "प्राथमिकता 2",

    // Progress Tracker
    trackerTitle: "लाइव समस्या प्रगति ट्रैकर",
    trackerSubtitle: "नागरिक समाधान के लिए रीयल-टाइम अमेज़न-स्टाइल डिलीवरी ट्रैकर",
    stageReported: "दर्ज व AI मूल्यांकित",
    stageAssigned: "विश्वविद्यालय टीम गठित",
    stageFunded: "प्रस्ताव व CSR अनुदान स्वीकृत",
    stageExecution: "मैदानी क्रियान्वयन व माइलस्टोन",
    stageResolved: "समाधान संपन्न व सत्यापित",
    stageCompleted: "पूर्ण",
    stageInProgress: "प्रगति पर",
    stageUpcoming: "आगामी",
    liveActivityFeed: "लाइव गतिविधि व माइलस्टोन ऑडिट फ़ीड",
    overallResolution: "कुल समाधान प्रगति",

    // Citizen Feedback & Verification
    feedbackTitle: "नागरिक समाधान सत्यापन और रेटिंग",
    feedbackSubtitle: "कृपया जमीनी समाधान की पुष्टि करें और विश्वविद्यालय टीम के कार्य को रेट करें।",
    rateSolution: "समाधान की गुणवत्ता और गति को स्टार दें:",
    feedbackPlaceholder: "समुदाय और राज्य परिषद को जमीनी प्रभाव बताएं (उदा. पानी अब पूरी तरह साफ और उपलब्ध है!)...",
    verifyGroundCheck: "मैं पुष्टि करता हूँ कि यह नागरिक समस्या जमीन पर सफलतापूर्वक हल हो चुकी है।",
    submitFeedbackBtn: "नागरिक सत्यापन और रेटिंग जमा करें",
    verifiedByCitizenBadge: "नागरिक द्वारा सत्यापित",
    citizenRatingLabel: "नागरिक संतुष्टि स्कोर",
    thankYouFeedback: "सत्यापन और रेटिंग देने के लिए धन्यवाद!",

    // University Pages
    uniDashboardTitle: "विश्वविद्यालय अनुसंधान एवं नवाचार केंद्र",
    uniDashboardSubtitle: "स्थानीय समस्याओं की जांच करें, छात्रों और प्रोफेसरों की बहुविषयक टीम बनाएं और शोध प्रस्ताव तैयार करें।",
    claimBtn: "समस्या का दावा करें",
    claimedBadge: "परिसर द्वारा दावा किया गया",
    pendingProposals: "CSR प्रतीक्षित प्रस्ताव",
    activeProjectsCount: "सक्रिय इंजीनियरिंग पायलट",
    assignedQueueTitle: "आने वाली परिसर समस्या कतार",

    // Industry Pages
    industryQueueTitle: "उद्योग CSR सामाजिक नवाचार कतार",
    industryQueueSubtitle: "विश्वविद्यालय शोध प्रस्तावों की समीक्षा करें, बजट माइलस्टोन का मूल्यांकन करें और सीएसआर अनुदान आवंटित करें।",
    sponsorProposalBtn: "प्रस्ताव प्रायोजित करें व अनुदान दें",
    fundingAllocated: "कुल आवंटित CSR अनुदान",
    fundedProjectsTitle: "उद्योग प्रायोजित परियोजनाएं",
    fundedProjectsSubtitle: "स्वीकृत शोध परियोजनाओं के माइलस्टोन, समयसीमा और सामाजिक प्रभाव की निगरानी करें।",

    // Industry Pages Additional
    csrEsgAnalytics: "कॉर्पोरेट CSR एवं ESG विश्लेषण",
    csrEsgSubtitle: "विश्वविद्यालय आधारित सामाजिक नवाचार अनुदान, एस्क्रो किश्तों और जमीनी प्रभाव की निगरानी।",
    reviewProposalsBtn: "प्रस्तावों की समीक्षा करें",
    totalGrantsCommitted: "कुल प्रतिबद्ध अनुदान",
    activeSponsoredProjects: "सक्रिय प्रायोजित परियोजनाएं",
    milestonesAchieved: "प्राप्त मील के पत्थर",
    disbursedViaEscrow: "एस्क्रो द्वारा वितरित",
    csrAllocationDomain: "क्षेत्रवार CSR आवंटन",
    csrScheduleSub: "सांविधिक CSR अनुसूची VII विषयों के अनुसार वितरण",
    grantDisbursementVelocity: "अनुदान वितरण गति",
    trancheReleasesSub: "सत्यापित मील के पत्थरों के आधार पर किश्त भुगतान",
    activePortfolios: "सक्रिय प्रायोजित परियोजना पोर्टफोलियो",
    liveInnovationSub: "मील के पत्थर वितरण और एस्क्रो नियंत्रण के साथ लाइव नवाचार पायलट",
    manageAllFunded: "सभी वित्तपोषित परियोजनाएं प्रबंधित करें →",
    progress: "प्रगति",
    grant: "अनुदान",
    industrySponsoredProjects: "उद्योग प्रायोजित परियोजनाएं",
    industrySponsoredSubtitle: "मील के पत्थरों की निगरानी करें, एस्क्रो किश्तें जारी करें और सामाजिक प्रभाव सत्यापित करें।",
    milestoneUpdated: "मील का पत्थर अद्यतित किया गया।",
    partnerHeis: "सहभागी संस्थान",
    sponsorship: "प्रायोजन",
    leadUni: "प्रमुख संस्थान",
    targetDeadline: "अंतिम तिथि",
    csrImpactCertBtn: "CSR इम्पैक्ट प्रमाणपत्र",
    milestoneCompletionVelocity: "मील का पत्थर पूर्णता गति",
    deliverables: "वितरण योग्य",
    csrEscrowSchedule: "CSR एस्क्रो किश्त संवितरण अनुसूची",
    disbursed: "संवितरित",
    tranche: "किश्त",
    releaseTrancheBtn: "किश्त जारी करें",
    milestoneDeliverablesHandover: "मील के पत्थर व जमीनी हैंडओवर",
    target: "लक्ष्य तिथि",
    viewReport: "रिपोर्ट देखें",
    noFundedProjectsYet: "अभी कोई स्वीकृत परियोजना सक्रिय नहीं है। विश्वविद्यालय समाधानों को प्रायोजित करने के लिए आने वाले प्रस्तावों पर जाएं।",

    // Proposal Wizard
    formulateProposalTitle: "समाधान प्रस्ताव तैयार करें",
    formulateProposalSubtitle: "उद्योग / सीएसआर फंडिंग भागीदारों को प्रस्तुत करने के लिए इंजीनियरिंग समाधान और मील के पत्थर का मसौदा तैयार करें।",
    stepScope: "परियोजना दायरा",
    stepTeam: "बहुविषयक टीम",
    stepNarrative: "प्रस्ताव विवरण",
    stepMilestones: "मील के पत्थर व समयसीमा",
    solutionTitleLabel: "परियोजना / समाधान का शीर्षक",
    expectedImpactLabel: "अपेक्षित सामुदायिक प्रभाव",
    expectedImpactPlaceholder: "उदा. 40,000+ दैनिक यात्रियों के जलभराव को समाप्त करता है और जलजनित बीमारियों को 85% कम करता है।",
    teamTitle: "छात्र एवं संकाय की बहुविषयक टीम गठित करें",
    teamSubtitle: "पूरक विषयों को एक साथ लाएं (उदा. सिविल इंजीनियरिंग + IoT/कंप्यूटर साइंस + पर्यावरण विज्ञान)।",
    methodologyLabel: "समाधान तकनीकी प्रस्ताव और कार्यप्रणाली",
    milestonesTimelineLabel: "मील के पत्थर और कार्यान्वयन समयसीमा",
    addMilestoneBtn: "+ अन्य मील का पत्थर जोड़ें",
    milestonePlaceholder: "मील का पत्थर वितरण योग्य",
    submitToIndustryBtn: "उद्योग भागीदारों को भेजें",

    // Admin Pages
    adminDashboardTitle: "राज्य स्तरीय नवाचार कमांड सेंटर",
    adminDashboardSubtitle: "समस्या रूटिंग, विश्वविद्यालय सहभागिता, सीएसआर अनुदान और समाधान गति की रीयल-टाइम निगरानी।",
    verifyAccountsTitle: "संस्थान एवं उपयोगकर्ता सत्यापन",
    verifyAccountsSubtitle: "विश्वविद्यालयों और सीएसआर कंपनियों के दस्तावेजों की जांच करें और अनुमोदन प्रदान करें।",
    exportCsvAudit: "CSV ऑडिट निर्यात करें",
    printSummaryReport: "सारांश रिपोर्ट प्रिंट करें",
    filterByDistrict: "जिले के अनुसार फ़िल्टर करें:",
    allDistrictsConsolidated: "झारखंड के सभी 24 जिले (समेकित)",
    reportedVsResolvedVelocity: "दर्ज बनाम हल की गई समस्याओं की गति",
    approveBtn: "स्वीकृत करें",
    rejectBtn: "अस्वीकार करें",
    accountVerificationsTab: "उपयोगकर्ता एवं संस्थान सत्यापन",
    csrCertApprovalsTab: "CSR प्रमाणपत्र अनुमोदन",
    certStatusCol: "प्रमाणपत्र स्थिति",
    certPendingApproval: "प्रशासक अनुमोदन प्रतीक्षित",
    certApproved: "अधिकृत / स्वीकृत",
    certRejected: "संशोधन का अनुरोध",
    approveCertBtn: "प्रमाणपत्र स्वीकृत करें",
    rejectCertBtn: "संशोधन का अनुरोध करें",
    previewCertBtn: "प्रमाणपत्र पूर्वावलोकन",
    downloadApprovedCertBtn: "स्वीकृत CSR प्रमाणपत्र डाउनलोड करें",
    previewDraftCertBtn: "मसौदा देखें (अनुमोदन लंबित)",
    certDraftWarning: "अनौपचारिक मसौदा — राज्य परिषद अनुमोदन प्रतीक्षित",
    certDraftAlertDesc: "यह परियोजना पूरी हो चुकी है, लेकिन यह प्रमाणपत्र कॉर्पोरेट ईएसजी टैक्स छूट या सीएसआर क्रेडिट के लिए तब तक मान्य नहीं है जब तक राज्य प्रशासन इसे अधिकृत नहीं करता।",
    certAdminApprovalSeal: "राज्य नवाचार परिषद आधिकारिक डिजिटल मुहर",
    certApprovedOn: "अधिकृत दिनांक",
    certSignedBy: "अधिकृत हस्ताक्षरकर्ता: राज्य नवाचार परिषद प्रशासक",
    noPendingCerts: "वर्तमान में कोई भी सीएसआर प्रमाणपत्र प्रशासनिक अनुमोदन के लिए लंबित नहीं है।",

    // Showcase & Help & Citizen & Map
    showcaseHeroBadge: "सामाजिक नवाचार प्रभाव शोकेस",
    showcaseHeroTitle: "परिसर अनुसंधान व CSR द्वारा हल की गई जमीनी समस्याएं",
    showcaseHeroSubtitle: "झारखंड भर में छात्र-शिक्षक टीमों द्वारा विकसित और कॉर्पोरेट सीएसआर भागीदारों द्वारा वित्तपोषित इंजीनियरिंग समाधान, कम लागत वाले प्रोटोटाइप और सामुदायिक तैनाती देखें।",
    allShowcases: "सभी शोकेस",
    helpCenterBadge: "सहायता केंद्र एवं ज्ञानकोश",
    helpCenterTitle: "अक्सर पूछे जाने वाले प्रश्न व सहायता",
    helpCenterSubtitle: "जानें कि कैसे सहयोग जमीनी नागरिक चुनौतियों को विश्वविद्यालय अनुसंधान टीमों और कॉर्पोरेट सीएसआर फंडिंग से जोड़ता है।",
    submitInquiryTitle: "सहायता अनुरोध भेजें",
    subjectLabel: "विषय / शीर्षक",
    categoryGeneral: "सामान्य पूछताछ",
    categoryTechnical: "तकनीकी / पोर्टल समस्याएं",
    categoryFunding: "CSR फंडिंग एवं एस्क्रो",
    inquiryMessageLabel: "विस्तृत संदेश",
    submitInquiryBtn: "अनुरोध जमा करें",
    submittingInquiry: "अनुरोध भेजा जा रहा है...",
    citizenDashboardTitle: "नागरिक प्रभाव डैशबोर्ड",
    activeReporterBadge: "सक्रिय रिपोर्टर",
    citizenWelcomePre: "वापसी पर स्वागत है,",
    citizenWelcomeSub: "अपनी नागरिक समस्याओं की प्रगति, स्थानीय समुदाय के समर्थन और विश्वविद्यालय समाधानों को ट्रैक करें।",
    exploreMapBtn: "नक्शा देखें",
    totalReportedCount: "कुल दर्ज समस्याएं",
    nearbyChallengesTitle: "निकटवर्ती नागरिक समस्याएं",
    upvote: "समर्थन करें",
    upvoted: "समर्थित",
    gisMapTitle: "राज्यव्यापी GIS नवाचार मानचित्र",
    gisMapSubtitle: "झारखंड भर में नागरिक चुनौतियों, विश्वविद्यालय निकटता और सीएसआर-वित्तपोषित परियोजनाओं का रीयल-टाइम भौगोलिक दृश्य।",
    legendUrgent: "उच्च / गंभीर",
    legendAssigned: "विश्वविद्यालय आवंटित",
    legendResolved: "हल व सत्यापित",
    allDistrictsCount: "सभी 24 जिले",
    autoRoutedCampus: "परिसर निकटता के आधार पर स्वतः रूटिंग",

    // Status Badges
    statusNew: "नई समस्या",
    statusUnderReview: "समीक्षाधीन",
    statusAssigned: "विश्वविद्यालय आवंटित",
    statusInProgress: "प्रगति पर",
    statusFunded: "अनुदान स्वीकृत",
    statusResolved: "हल व सत्यापित",
    priorityHigh: "उच्च प्राथमिकता",
    priorityMedium: "मध्यम प्राथमिकता",
    priorityLow: "सामान्य प्राथमिकता",
  },

  // Jharkhand Regional Language: Khortha (खोरठा)
  kht: {
    // TopBar & Header
    searchPlaceholder: "समस्या, शोध प्रोजेक्ट, यूनिवर्सिटी, सीएसआर साथी खोजा...",
    liveNotifications: "ताज़ा सूचना सब",
    markAllRead: "सभे पढ़ल चिह्नित करा",
    noNotifications: "कौनों नया सूचना नय हे।",
    viewProgressTracker: "चाल-चलन ट्रैकर देखा →",
    signOut: "लॉग आउट करा",
    language: "भाषा",
    signedInAs: "लॉग इन करल नाम",
    role: "भूमिका",
    organization: "संस्थान / कंपनी",
    district: "जिला",

    // Roles
    citizen: "नागरिक / जनता",
    govtOrg: "सरकारी / स्थानीय संस्था",
    govt_org: "सरकारी / स्थानीय संस्था",
    university: "विश्वविद्यालय / कॉलेज",
    industry: "उद्योग / CSR साथी",
    admin: "राज्य नवाचार परिषद (एडमिन)",

    // Navigation & Sidebar
    portalBrand: "सहयोग",
    portalSubtitle: "सामाजिक नवाचार पोर्टल",
    navCitizenDashboard: "डैशबोर्ड",
    navMyIssues: "हमर रिपोर्ट",
    navReportIssue: "समस्या दर्ज करा",
    navGisMap: "राज्य नक्शा",
    navShowcase: "शोकेस",
    navHelpFaq: "मदद",
    navUniDashboard: "डैशबोर्ड",
    navCampusQueue: "स्थानीय समस्या",
    navProjects: "प्रोजेक्ट",
    navCsrDashboard: "CSR डैशबोर्ड",
    navCsrQueue: "प्रस्ताव",
    navFundedProjects: "स्वीकृत",
    navAdminAnalytics: "राज्य भरक विश्लेषण",
    navVerifyAccounts: "अनुमोदन",
    navAdminIssues: "मास्टर समस्या कंसोल",
    navAdminAudit: "सिस्टम ऑडिट लॉग",
    navWorkflow: "वर्कफ़्लो",
    workflowSubtitle: "यूनिवर्सिटी, उद्योग आरु सरकार के बीच प्रोजेक्ट सहयोग नोट्स।",
    workflowNotes: "वर्कफ़्लो नोट्स",
    workflowCreateNote: "नया नोट",
    workflowEditNote: "नोट संपादित करा",
    workflowNoteTitle: "नोटक शीर्षक",
    workflowNoteContent: "वर्कफ़्लो नोटक सामग्री...",
    workflowSave: "बदलाव सेव करा",
    workflowCreate: "नोट बनावा",
    workflowCancel: "रद्द करा",
    workflowNoProjects: "कोनो प्रोजेक्ट उपलब्ध नै",
    workflowNoProjectsHint: "यूनिवर्सिटी प्रोजेक्ट दावा करे के बाद वर्कफ़्लो नोट्स उपलब्ध होतय।",
    workflowNoNotes: "अभी कोनो वर्कफ़्लो नोट नै",
    workflowNoNotesHint: "यूनिवर्सिटी टीम अपन प्रोजेक्ट प्रगति ट्रैक करे लेल नोट्स बनावथी।",
    workflowSelectNote: "पूरा सामग्री देखे लेल बाईं के नोट चुना।",
    workflowSuggestChange: "बदलाव सुझावा",
    workflowSuggestPlaceholder: "अपन सुझाव लिखा...",
    workflowSubmitSuggestion: "सुझाव भेजा",
    workflowSuggestions: "व्यावसायिक सुझाव",
    networkOverview: "सहयोग नेटवर्क",
    networkActive: "सक्रिय",
    ctaReportCivic: "+ नागरिक समस्या दर्ज करा",
    ctaExploreQueue: "समस्या कतार देखा",

    // Workflow Module
    workflowPageTitle: "परियोजना वर्कफ़्लो",
    workflowPageSubtitle: "देखा कि यूनिवर्सिटी हेकर समस्या विवरण पर कइसे आगे बढ़त हे आरु CSR फीडबैक पर कइसे जवाब देत हे।",
    workflowSelectProject: "शुरू करे लेल एक परियोजना चुना",
    workflowSelectProjectHint: "नीचे अपन एक परियोजना चुन के ओकर वर्कफ़्लो नोट आरु सुझाव देखा।",
    workflowNoProjects: "तोहार खाता लेल अभी कौनों परियोजना नय हे।",
    workflowNoProjectsHint: "जब यूनिवर्सिटी कौनों रूट भेल समस्या लेल टीम बनावत हे, तब परियोजना सब एतहां देखायत हे।",
    workflowNotesTab: "वर्कफ़्लो नोट",
    workflowSuggestionsTab: "व्यापार सुझाव",
    workflowNewNote: "नया नोट",
    workflowEditNote: "नोट संपादन करा",
    workflowDeleteNote: "नोट हटावा",
    workflowNoteTitle: "नोटक शीर्षक",
    workflowNoteTitlePlaceholder: "उदा. काम करेक रोडमैप आरु साइट बेसलाइन",
    workflowNoteContent: "नोटक सामग्री",
    workflowNoteContentPlaceholder: "ई परियोजनाक योजना, तकनीकी फैसला, प्रगति आरु अगला चरण लिखा...",
    workflowSampleSuggestion: "ESG रिपोर्टिंग लेल जियोटैग प्रगति अपडेट",
    workflowSaveNote: "नोट सहेजा",
    workflowSavingNote: "सहेजे जा रहल हे...",
    workflowCancelEdit: "रद्द करा",
    workflowNoNotes: "अभी कौनों वर्कफ़्लो नोट नय हे।",
    workflowNoNotesHintUni: "टीम ई समस्या विवरण से कइसे निपटत हे, ओकर पहिला नोट बनावा।",
    workflowNoNotesHintOther: "मालिक यूनिवर्सिटी वर्कफ़्लो नोट एतहां साझा करतो।",
    workflowSuggestChange: "परिवर्तन सुझावा",
    workflowSuggestionPlaceholder: "ऊ परिवर्तन या सलाह बतावा जे तोहरे यूनिवर्सिटी टीम सं विचार करावे चाही...",
    workflowSubmitSuggestion: "सुझाव जमा करा",
    workflowSubmitting: "जमा हो रहल हे...",
    workflowSuggestionStatus: "स्थिति",
    workflowPending: "बाकी",
    workflowReviewed: "जांचल",
    workflowAccepted: "स्वीकारल",
    workflowRejected: "नय मानल",
    workflowMarkReviewed: "जांचल करा",
    workflowApprove: "मंजूर करा",
    workflowReject: "मना करा",
    workflowNoSuggestions: "ई नोट पर अभी कौनों व्यापार सुझाव नय हे।",
    workflowNoSuggestionsHintUni: "जब CSR साथी बदलावक सलाह देत हे, तब एतहां जांच, मंजूरी या मना करा।",
    workflowNoSuggestionsHintBiz: "अगर तोहें चाहबा कि यूनिवर्सिटी टीम बदलाव पर विचार करोक, त ई नोट पर सुझाव भेजा।",
    workflowSuggestedBy: "सुझाव देल",
    workflowUpdatedAt: "अपडेट",
    workflowCreatedAt: "बनल",
    workflowLoading: "वर्कफ़्लो लोड हो रहल हे...",
    workflowErrorLoad: "वर्कफ़्लो लोड नय भेल पारल। फेरु से कोसिस करा।",
    workflowAccessDenied: "तोहें वर्कफ़्लो क्षेत्र में जाये के अधिकार नय हके।",
    workflowNoteDeleted: "वर्कफ़्लो नोट हटा दील गेल।",
    workflowNoteSaved: "वर्कफ़्लो नोट सहेज दील गेल।",
    workflowSuggestionSent: "सुझाव यूनिवर्सिटी टीम के भेज दील गेल।",
    workflowStatusUpdated: "सुझावक स्थिति अपडेट भेल।",
    workflowBackToProjects: "परियोजना सब पर वापस जा",
    workflowUniBadge: "यूनिवर्सिटी",
    workflowBizBadge: "CSR साथी",
    workflowAdminBadge: "निगरानी",
    workflowViewOnly: "तोहें ई वर्कफ़्लो सिर्फ पढ़े के मोड में देख रहल हका।",
    workflowYouOwn: "तोहें ई परियोजनाक मालिक यूनिवर्सिटी हका।",
    workflowYouSponsor: "तोहें ई परियोजनाक CSR साथी हका।",
    workflowCanvasTab: "व्हाइटबोर्ड",
    workflowObjects: "ऑब्जेक्ट",
    workflowEmptyCanvas: "कौनों कैनवास नय",
    workflowCanvasSaved: "व्हाइटबोर्ड सहेज दील गेल।",
    wbSave: "व्हाइटबोर्ड सहेजा",
    wbSaving: "सहेजे जा रहल हे...",
    wbSaved: "सहेजल",
    wbUnsaved: "असहेजל बदलाव",
    wbUndo: "पहिने करा",
    wbClear: "साफ़ करा",
    wbViewOnly: "सिर्फ देखा",
    wbViewOnlyHint: "ई यूनिवर्सिटीक वर्कफ़्लो व्हाइटबोर्डक साझा रीड-ओनली दृश्य हे।",
    wbEmpty: "तोहार व्हाइटबोर्ड खाली हे",
    wbEmptyHint: "ऊपर सं पेन, आकृति या टेक्स्ट टूल चुन के वर्कफ़्लो बनावा शुरू करा।",
    wbEmptyView: "वर्कफ़्लो व्हाइटबोर्ड खाली हे",
    wbEmptyViewHint: "मालिक यूनिवर्सिटी अभी एतहां कौनों नय बनौलों।",
    wbTextPlaceholder: "टेक्स्ट लिखा...",
    wbMoveTool: "चुना / जगह बदला",
    wbMoveHint: "सलाह: Select टूल चुनबा, फेरु कोनों आकृति, तीर या फ्रीहैंड रेखा के खींच के अउर कहूं ले चला।",

    // Design Thinking Board
    boardTitle: "सहयोग बोर्ड",
    boardBack: "परियोजना पर वापस",
    execWorkflowTitle: "कार्यान्वनिस कार्यप्रवाह",
    execWorkflowSubtitle: "साझा व्हाइटबोर्ड — कार्यान्वनिस योजना, समयसारणी अने ज़िम्मेदारी बना। यूनिवर्सिटी लिख अने संपादित कर सकत हें; बिज़नेस साझेदार परिवर्तन लाइव देख सकत हें।",
    execWorkflowEditable: "यूनिवर्सिटी लेल संपादन योग्य",
    execWorkflowReadOnly: "बिज़नेस साझेदार लेल केवल देखने लेल",
    execChecklistTitle: "कार्यान्वनिस सूची — संसाधन ज़रूरत कैनवास",
    execChecklistSubtitle: "आपकर प्रोजेक्ट को योजना से मैदान तक लै जावे लेल ज़रूरी हर संसाधन, जाकर यूनिवर्सिटी अनुरोध करे हे अने बिज़नेस साझेदार पूरा करे हे। जव तक बिज़नेस उ प्रदान ने करे ताक हें, आइटम सूची में बने रहे हें।",
    execChecklistAdd: "संसाधन अनुरोध करा",
    execChecklistAddTitle: "संसाधन के अनुरोध करा",
    execChecklistEditTitle: "ए अनुरोध के संपादित करा",
    execChecklistAddItem: "सूची में जोड़ा",
    execChecklistSave: "बदलाव सहेजा",
    execChecklistSaving: "सहेजे जा रहल हे…",
    execChecklistCancel: "रद्द करा",
    execChecklistItemPh: "प्रोजेक्ट के का चाहिए? जैसे 5000 लीटर/दिन जल शोधन इकाई",
    execChecklistWhyPh: "हमन ले एक आवश्यकता काहिए हे? बता कि कार्यान्वनिस में कैसे मदद करे…",
    execChecklistProgress: "कार्यान्वनिस प्रगति",
    execChecklistEmpty: "अबे कौनों संसाधन अनुरोध नय",
    execChecklistEmptyUni: "उ सामग्री, उपकरण अने सहायता जोड़ा जेकर आपन टीम के प्रोजेक्ट को मैदान तक लै जावे लेल ज़रूरत हे।",
    execChecklistEmptyBiz: "यूनिवर्सिटी ने अबे कौनों संसाधन अनुरोध ने करल हे। नय अनुरोध इथे दिसत हें।",
    execChecklistWhy: "हमन ले एक आवश्यकता काहिए हे:",
    execChecklistRequestedBy: "अनुरोधकर्ता",
    execChecklistProvidedBy: "द्वारा प्रदान",
    execChecklistProvide: "ए संसाधन प्रदान करा",
    execChecklistProvided: "प्रदान करल गेल",
    execChecklistEdit: "संपादित करा",
    execChecklistDelete: "हटावा",
    execChecklistDeleteConfirm: "ए अनुरोध के सूची से हटावा?",
    boardDeniedHint: "वर्कफ़्लो बोर्ड सिर्फ मालिक यूनिवर्सिटी टीम आरू उनकर उद्योग साथी लेल निजी हे।",
    boardNewNote: "नया नोट",
    boardAddGuidance: "मार्गदर्शन जोड़ा",
    boardAddNote: "नोट जोड़ा",
    boardEditTitle: "नोट संपादित करा",
    boardEdit: "संपादित करा",
    boardDelete: "हटावा",
    boardDeleteConfirm: "ई नोट के हटाबा?",
    boardSave: "बदलाव सहेजा",
    boardSaving: "सहेजा जा रहल हे...",
    boardCancel: "रद्द करा",
    boardCreated: "बनल",
    boardPickColumn: "ई नोट कहाँ जाये?",
    boardPickHintUni: "डिज़ाइन थिंकिंग के ओइ चरण चुना जेहिमें तोहें ई नोट जोड़ना चाहत हका।",
    boardPickHintBiz: "अपन मार्गदर्शन या अनुरोध जोड़ा, जे पर यूनिवर्सिटी टीम विचार करू।",
    boardNoteTitle: "छोटा शीर्षक (वैकल्पिक)",
    boardNoteContent: "अपन नोट लिखा... विचार, प्रतिक्रिया या डेटा",
    boardGuidancePlaceholder: "यूनिवर्सिटी टीम के संग मार्गदर्शन या अनुरोध साझा करा...",
    boardCreateBizHint: "ई Business मार्गदर्शन के रूप में चिह्नित होये। बोर्ड के प्रबंधन यूनिवर्सिटी टीम करथे।",
    boardViewOnlyBiz: "CSR साथी लेल सिर्फ़ देखे के अधिकार। तोहें मार्गदर्शन नोट जोड़ सकत हका, पर सिर्फ यूनिवर्सिटी टीम नोट संपादित या स्थानांतरित कर सकत हे।",
    boardEditColumn: "चरण में ले जाया",
    boardAuthorUni: "यूनिवर्सिटी",
    boardAuthorBiz: "Business",
    boardEmptyHint: "अब तक कौनों स्टिकी नोट नय।",
    boardEmptyClickHint: "पहिलो नोट जोड़े लेल क्लिक करा",
    board_empathize: "सहानुभूति",
    board_define: "परिभाषित करा",
    board_ideate: "विचार करा",
    board_prototype: "प्रोटोटाइप",
    board_test: "परीक्षण",
    board_empathize_hint: "उपयोगकर्ता आरू संदर्भ के समझा",
    board_define_hint: "मुख्य समस्या निर्धारित करा",
    board_ideate_hint: "संभावना उत्पन्न करा",
    board_prototype_hint: "ठोस मॉडल बनावा",
    board_test_hint: "वास्तविकता से सत्यापित करा",

    // Landing Page
    heroBadge: "AI-चलवइया सामाजिक नवाचार मंच",
    heroTitlePre: "झारखंडक नागरिक समस्या के जोड़ना ",
    heroTitleHighlight: "यूनिवर्सिटी आरु उद्योग साथी से",
    heroSubtitle: "नागरिक फोटो आरु थोड़का बात लिख के समस्या दर्ज करथीन। हमर AI इंजन समस्या के जांच के नजदीकी यूनिवर्सिटी सब के भेज देहे, जहां प्रोफेसर-छात्र मिल के CSR अनुदान से समाधान बनावथीन।",
    reportCivicBtn: "समस्या दर्ज करा",
    loginBtn: "यूनिवर्सिटी / उद्योग लॉगिन",
    adminLoginBtn: "एडमिन लॉगिन",
    signIn: "लॉगिन करा",
    joinNetwork: "नेटवर्क में जुड़ा",
    heroCheck1: "AI समस्या सूत्रीकरण",
    heroCheck2: "नजदीकी यूनिवर्सिटी रूटिंग",
    heroCheck3: "जनता के तुरंत खबर",
    liveActivity: "मंचक लाइव गतिविधि",
    liveActivitySample: "टाटा स्टील CSR लेल फ्लोराइड शुद्धिकरण पायलट",
    liveActivitySampleSub: "बीआईटी मेसरा के मिलल · निकटतम कैंपस (12.4 किमी) · 60 दिनक समय",
    howItWorks: "सहयोग कइसे काम करहे",
    fromReportToResolution: "समस्या दर्ज से ले के जमीन पर समाधान तक",
    workflowStep1Title: "1. नागरिक रिपोर्टिंग",
    workflowStep1Desc: "नागरिक फोटो आरु स्थान के साथे अपन गांव/मुहल्लाक समस्या दर्ज करथीन।",
    workflowStep2Title: "2. AI जांच आरु रूटिंग",
    workflowStep2Desc: "AI समस्याक गंभीरता जांचे हे आरु नजदीकी यूनिवर्सिटी के सीधे भेज देहे।",
    workflowStep3Title: "3. यूनिवर्सिटी समाधान",
    workflowStep3Desc: "प्रोफेसर आरु छात्र मिल के इंजीनियरिंग प्रोटोटाइप आरु समाधान बनावथीन।",
    workflowStep4Title: "4. उद्योग CSR अनुदान आरु समाधान",
    workflowStep4Desc: "उद्योग साथी पैसा देके प्रोजेक्ट पूरा करावथीन आरु जनता के खबर मिल जाय हे।",
    platformImpactDashboard: "झारखंड प्रभाव डैशबोर्ड",
    realtimeIndicators: "सभे जिला के रीयल-टाइम आंकड़े",
    viewFullAnalytics: "पूरा विश्लेषण देखा →",
    copyrightFooter: "© 2026 सहयोग — सामाजिक नवाचार सहभागिता मंच। सभे अधिकार सुरक्षित।",
    collabCivicSolving: "मिल-जुल के समस्या समाधान",

    // Auth (Login & Signup)
    welcomeBack: "सहयोग में तोहर स्वागत हे",
    signInWorkspace: "अपन सहभागिता डैशबोर्ड में लॉगिन करा।",
    continueGoogle: "Google से आगे बढ़ा",
    continueCredentials: "या ईमेल आरु पासवर्ड से लॉगिन करा",
    quickDemoSwitcher: "डेमो खाता चुनवा:",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    signInToDashboard: "डैशबोर्ड में घुसा",
    signingIn: "लॉगिन भेल लागल हे...",
    newToSahayog: "सहयोग में नया हका?",
    createAnAccount: "नया खाता बनावा",
    alreadyHaveAccount: "पहिले से खाता हे?",
    joinSahayogNetwork: "सहयोग नेटवर्क में जुड़ा",
    fullName: "पूरा नाम",
    selectRole: "अपन भूमिका चुना",
    institutionName: "यूनिवर्सिटी / कंपनी के नाम",
    department: "विभाग / CSR शाखा",

    // Report Issue Wizard
    reportTitle: "नागरिक समस्या दर्ज करा",
    reportSubtitle: "फोटो आरु थोड़का विवरण दा। हमर AI इंजन शोध विवरण बना के नजदीकी यूनिवर्सिटी के भेजतो।",
    stepBasic: "मूल जानकारी",
    stepDesc: "समस्याक विवरण",
    stepPhoto: "फोटो प्रमाण",
    stepLocation: "जगह / स्थान",
    stepReview: "AI जांच आरु समीक्षा",
    issueTitleLabel: "समस्याक शीर्षक",
    issueTitlePlaceholder: "उदा. अल्बर्ट एक्का चौक पर नाली जाम आरु पानी भराव",
    categoryLabel: "समस्याक श्रेणी",
    selectCategory: "श्रेणी चुना",
    descLabel: "समस्याक संक्षिप्त विवरण",
    descPlaceholder: "उदा. बरसात में नाली सड़क पर बहे लागल हे, 300 मीटर तक रास्ता बंद हे...",
    descTip: "सुझाव: विवरण छोट राखा! ककरा परेशानी हे आरु कतेक दिन से हे, सेकर उल्लेख करा। सहयोग AI मॉडल यूनिवर्सिटी लेल फॉर्मल समस्या विवरण तैयार करतो।",
    photoLabel: "फोटो / प्रमाण अपलोड करा",
    photoSubtitle: "फोटो से AI बाढ़ खतरा आरु जरूरी स्कोर जांचे हे।",
    districtLabel: "जिला (झारखंड)",
    blockLabel: "प्रखंड / निकाय",
    blockPlaceholder: "उदा. कांके / तमाड़ / जमशेदपुर",
    landmarkLabel: "सड़क / लैंडमार्क",
    landmarkPlaceholder: "उदा. अल्बर्ट एक्का चौक लगे",
    pinLocationMap: "नक्शा पर सही जगह चुना (यूनिवर्सिटी दूरी लेल)",
    useGps: "अखनक GPS स्थान लेवा",
    aiSynthesizing: "AI शोध विवरण तैयार भेल लागल हे...",
    aiFormulatedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या आरु गंभीरता",
    regenerateAi: "फेरु से AI बनावा",
    publicRisk: "जनताक जोखिम",
    urgencyLevel: "तात्कालिकता",
    compositeScore: "कुल गंभीरता स्कोर",
    backBtn: "पाछे",
    continueBtn: "आगे बढ़ा",
    submitBtn: "नजदीकी यूनिवर्सिटी सब के भेजो",
    submittingBtn: "सहयोग नेटवर्क पर प्रकाशित भेल लागल हे...",

    // My Reported Challenges
    myReportedChallenges: "हामर दर्ज करल समस्या सब",
    myReportedSubtitle: "समस्या मूल्यांकन, यूनिवर्सिटी टीम, उद्योग अनुदान आरु समाधान माइलस्टोन के देखा।",
    reportNewChallenge: "नया समस्या दर्ज करा",
    noReportedIssues: "तोहें अभी तक कौनों समस्या दर्ज नय करले ह।",
    noReportedHelper: "AI जांच शुरू करे लेल आरु नजदीकी यूनिवर्सिटी तक पहुंचावे लेल अपन जिलाक समस्या फोटो सहित दर्ज करा।",

    // Issue Detail
    citizenDescription: "नागरिक द्वारा देल विवरण",
    aiSynthesizedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या",
    evidencePhotos: "फोटो प्रमाण व अपलोड",
    nearestRoutingTitle: "नजदीकी यूनिवर्सिटी आरु दूरी रूटिंग",
    assembleTeamTitle: "बहुविषयक टीम बनावा",
    assembleTeamSubtitle: "समाधान प्रस्ताव बनावे लेल अलग-अलग विभागक छात्र आरु प्रोफेसर के टीम बनावा।",
    saveTeamDraftProposal: "टीम सुरक्षित करा आरु प्रस्ताव बनावा",
    exportCsrCert: "CSR इम्पैक्ट प्रमाणपत्र",
    claimChallenge: "यूनिवर्सिटी लेल दावा करा",
    claiming: "दावा दर्ज भेल लागल हे...",
    nearestCampus: "सबले नियरे कैंपस",
    kmFromCampus: "किमी दूर कैंपस से",
    priority1: "प्राथमिकता 1",
    priority2: "प्राथमिकता 2",

    // Progress Tracker
    trackerTitle: "लाइव समस्या चाल-चलन ट्रैकर",
    trackerSubtitle: "नागरिक समस्या समाधान लेल रीयल-टाइम अमेज़न-स्टाइल डिलीवरी ट्रैकर",
    stageReported: "दर्ज व AI जांचल",
    stageAssigned: "यूनिवर्सिटी टीम बनल",
    stageFunded: "प्रस्ताव व CSR अनुदान पास",
    stageExecution: "मैदान में काम व माइलस्टोन",
    stageResolved: "समाधान संपन्न व जांचल",
    stageCompleted: "पूरा भेल",
    stageInProgress: "काम चल रहल हे",
    stageUpcoming: "आगे अइतो",
    liveActivityFeed: "लाइव गतिविधि व माइलस्टोन ऑडिट फ़ीड",
    overallResolution: "कुल समाधान प्रगति",

    // Citizen Feedback & Verification
    feedbackTitle: "नागरिक समाधान जांच आरु रेटिंग",
    feedbackSubtitle: "जमीन पर काम भेल हे कि नय, सेकर पुष्टि करा आरु यूनिवर्सिटी टीम के रेट करा।",
    rateSolution: "समाधान के गति आरु काम के स्टार दा:",
    feedbackPlaceholder: "समुदाय आरु राज्य परिषद के जमीनी प्रभाव बतावा (उदा. पानी अखन पूरा साफ आरु चालू हे!)...",
    verifyGroundCheck: "हम पुष्टि करहियो कि ई नागरिक समस्या जमीन पर पूरा हल भेल हे।",
    submitFeedbackBtn: "जांच आरु रेटिंग जमा करा",
    verifiedByCitizenBadge: "नागरिक द्वारा जांचल",
    citizenRatingLabel: "नागरिक संतुष्टि स्कोर",
    thankYouFeedback: "जांच आरु रेटिंग देवे लेल धन्यवाद!",

    // University Pages
    uniDashboardTitle: "विश्वविद्यालय अनुसंधान एवं नवाचार केंद्र",
    uniDashboardSubtitle: "स्थानीय समस्याक जांच करा, छात्र-प्रोफेसरक बहुविषयक टीम बनावा आरु शोध प्रस्ताव तैयार करा।",
    claimBtn: "समस्या पर दावा करा",
    claimedBadge: "कैंपस द्वारा दावा करल",
    pendingProposals: "CSR प्रतीक्षित प्रस्ताव",
    activeProjectsCount: "चालू इंजीनियरिंग पायलट",
    assignedQueueTitle: "आवे वाला कैंपस समस्या कतार",

    // Industry Pages
    industryQueueTitle: "उद्योग CSR सामाजिक नवाचार कतार",
    industryQueueSubtitle: "यूनिवर्सिटी शोध प्रस्ताव के देखा, बजट माइलस्टोन जाँचा आरु CSR अनुदान पास करा।",
    sponsorProposalBtn: "प्रस्ताव स्पॉन्सर करा व पैसा दा",
    fundingAllocated: "कुल देल CSR अनुदान",
    fundedProjectsTitle: "उद्योग संपोषित प्रोजेक्ट सब",
    fundedProjectsSubtitle: "स्वीकृत शोध प्रोजेक्ट के माइलस्टोन, समय आरु सामाजिक प्रभाव के देखा।",

    // Industry Pages Additional
    csrEsgAnalytics: "कॉर्पोरेट CSR आरु ESG विश्लेषण",
    csrEsgSubtitle: "यूनिवर्सिटी सामाजिक नवाचार अनुदान, किश्त भुगतान आरु जमीनी प्रभाव के देखा।",
    reviewProposalsBtn: "प्रस्ताव सब जाँचा",
    totalGrantsCommitted: "कुल देल अनुदान",
    activeSponsoredProjects: "चालू संपोषित प्रोजेक्ट",
    milestonesAchieved: "पूरा भेल पड़ाव",
    disbursedViaEscrow: "एस्क्रो से देल रकम",
    csrAllocationDomain: "क्षेत्रवार CSR बंटवारा",
    csrScheduleSub: "CSR अनुसूची VII के अनुसार हिसाब",
    grantDisbursementVelocity: "अनुदान देवेक गति",
    trancheReleasesSub: "काम जांच के किश्त भुगतान",
    activePortfolios: "चालू संपोषित प्रोजेक्ट लिस्ट",
    liveInnovationSub: "पड़ाव आरु किश्त नियंत्रण के साथे लाइव नवाचार काम",
    manageAllFunded: "सभे स्वीकृत प्रोजेक्ट देखा →",
    progress: "प्रगति",
    grant: "अनुदान",
    industrySponsoredProjects: "उद्योग संपोषित प्रोजेक्ट सब",
    industrySponsoredSubtitle: "काम के पड़ाव देखा, किश्त रिलीज करा आरु सामाजिक असर जाँचा।",
    milestoneUpdated: "पड़ाव अपडेट भेल।",
    partnerHeis: "साथी यूनिवर्सिटी",
    sponsorship: "अनुदान रकम",
    leadUni: "मुख्य यूनिवर्सिटी",
    targetDeadline: "अंतिम तारीख",
    csrImpactCertBtn: "CSR इम्पैक्ट प्रमाणपत्र",
    milestoneCompletionVelocity: "काम पूरा होवेक गति",
    deliverables: "जमा करेक काम",
    csrEscrowSchedule: "CSR किश्त भुगतान हिसाब",
    disbursed: "देल गेल",
    tranche: "किश्त",
    releaseTrancheBtn: "किश्त रिलीज करा",
    milestoneDeliverablesHandover: "काम के पड़ाव आरु हैंडओवर",
    target: "लक्ष्य तारीख",
    viewReport: "रिपोर्ट देखा",
    noFundedProjectsYet: "अभी कौनों प्रोजेक्ट स्वीकृत नय हे। यूनिवर्सिटी समाधान के स्पॉन्सर करे लेल आवे वाला प्रस्ताव देखा।",

    // Proposal Wizard
    formulateProposalTitle: "समाधान प्रस्ताव बनावा",
    formulateProposalSubtitle: "उद्योग / CSR साथी सब के भेजे लेल इंजीनियरिंग समाधान आरु पड़ाव तैयार करा।",
    stepScope: "प्रोजेक्ट दायरा",
    stepTeam: "बहुविषयक टीम",
    stepNarrative: "प्रस्ताव विवरण",
    stepMilestones: "पड़ाव आरु समय",
    solutionTitleLabel: "प्रोजेक्ट / समाधान के नाम",
    expectedImpactLabel: "जनता पर असर",
    expectedImpactPlaceholder: "उदा. 40,000+ लोग के जलजमाव से मुक्ति आरु बीमारी 85% कम करतो।",
    teamTitle: "छात्र-प्रोफेसर के बहुविषयक टीम बनावा",
    teamSubtitle: "अलग-अलग विभाग के लोग के साथे लाबा (उदा. सिविल इंजीनियरिंग + IoT + पर्यावरण विज्ञान)।",
    methodologyLabel: "तकनीकी समाधान आरु तरीका",
    milestonesTimelineLabel: "काम के पड़ाव आरु समयसीमा",
    addMilestoneBtn: "+ आरु पड़ाव जोड़ा",
    milestonePlaceholder: "पड़ाव के काम",
    submitToIndustryBtn: "उद्योग साथी सब के भेजो",

    // Admin Pages
    adminDashboardTitle: "राज्य भरक नवाचार कमांड सेंटर",
    adminDashboardSubtitle: "समस्या रूटिंग, यूनिवर्सिटी भागीदारी, CSR अनुदान आरु समाधान गतिक रीयल-टाइम निगरानी।",
    verifyAccountsTitle: "संस्थान आरु यूजर जांच",
    verifyAccountsSubtitle: "यूनिवर्सिटी आरु CSR कंपनी सब के कागजात जाँचा आरु मंजूरी दा।",
    exportCsvAudit: "CSV ऑडिट डाउनलोड करा",
    printSummaryReport: "रिपोर्ट प्रिंट करा",
    filterByDistrict: "जिला अनुसार छांटा:",
    allDistrictsConsolidated: "झारखंडक सभे 24 जिला",
    reportedVsResolvedVelocity: "दर्ज आरु हल भेल समस्या गति",
    approveBtn: "मंजूरी दा",
    rejectBtn: "मना करा",
    accountVerificationsTab: "यूजर आरु संस्थान जांच",
    csrCertApprovalsTab: "CSR सर्टिफिकेट मंजूरी",
    certStatusCol: "सर्टिफिकेट स्थिति",
    certPendingApproval: "एडमिन मंजूरी बाकी",
    certApproved: "मंजूर भेल",
    certRejected: "सुधार के अनुरोध",
    approveCertBtn: "सर्टिफिकेट मंजूर करा",
    rejectCertBtn: "सुधार के अनुरोध करा",
    previewCertBtn: "सर्टिफिकेट देखल जाय",
    downloadApprovedCertBtn: "मंजूर CSR सर्टिफिकेट डाउनलोड करा",
    previewDraftCertBtn: "कच्चा सर्टिफिकेट देखा (मंजूरी बाकी)",
    certDraftWarning: "कच्चा ड्राफ्ट — राज्य परिषद एडमिन मंजूरी के अगोर हे",
    certDraftAlertDesc: "ई प्रोजेक्ट पूरा भ गेल हे, लेकिन ई सर्टिफिकेट कॉर्पोरेट CSR छूट लेल तब तक मान्य नञ् हे जब तक राज्य प्रशासन एकरा मंजूरी नञ् दे हे।",
    certAdminApprovalSeal: "राज्य नवाचार परिषद डिजिटल मुहर",
    certApprovedOn: "मंजूरी तारीख",
    certSignedBy: "अधिकृत दस्तखत: राज्य नवाचार परिषद एडमिन",
    noPendingCerts: "एखनी कोनो CSR सर्टिफिकेट एडमिन मंजूरी लेल बाकी नखे।",

    // Showcase & Help & Citizen & Map
    showcaseHeroBadge: "सामाजिक नवाचार प्रभाव शोकेस",
    showcaseHeroTitle: "यूनिवर्सिटी शोध आरु CSR से हल भेल समस्या सब",
    showcaseHeroSubtitle: "झारखंड भर में छात्र-प्रोफेसर टीम द्वारा बनल आरु CSR कंपनी सब द्वारा फंड करल जमीनी समाधान आरु प्रोटोटाइप देखा।",
    allShowcases: "सभे शोकेस",
    helpCenterBadge: "मदद केंद्र आरु ज्ञानकोश",
    helpCenterTitle: "अक्सर पुछल सवाल आरु मदद",
    helpCenterSubtitle: "जाना कि सहयोग कइसे नागरिक समस्या के यूनिवर्सिटी रिसर्च आरु CSR अनुदान से जोड़े हे।",
    submitInquiryTitle: "मदद लेल लिख के भेजो",
    subjectLabel: "विषय / बात",
    categoryGeneral: "साधारण पूछताछ",
    categoryTechnical: "तकनीकी समस्या",
    categoryFunding: "CSR अनुदान आरु एस्क्रो",
    inquiryMessageLabel: "पूरा बात",
    submitInquiryBtn: "संदेश भेजो",
    submittingInquiry: "संदेश जा रहल हे...",
    citizenDashboardTitle: "नागरिक प्रभाव डैशबोर्ड",
    activeReporterBadge: "सक्रिय नागरिक",
    citizenWelcomePre: "फेरु स्वागत हे,",
    citizenWelcomeSub: "अपन दर्ज समस्या, स्थानीय वोट आरु यूनिवर्सिटी समाधान के देखा।",
    exploreMapBtn: "नक्शा देखा",
    totalReportedCount: "कुल दर्ज समस्या",
    nearbyChallengesTitle: "आस-पास के समस्या सब",
    upvote: "समर्थन करा",
    upvoted: "समर्थन देल",
    gisMapTitle: "राज्य भरक GIS नवाचार नक्शा",
    gisMapSubtitle: "झारखंड भर में नागरिक समस्या, यूनिवर्सिटी दूरी आरु CSR प्रोजेक्ट के रीयल-टाइम नक्शा।",
    legendUrgent: "भारी जरूरी",
    legendAssigned: "यूनिवर्सिटी मिलल",
    legendResolved: "हल भेल व जांचल",
    allDistrictsCount: "सभे 24 जिला",
    autoRoutedCampus: "कैंपस दूरी के हिसाब से सीधा रूटिंग",

    // Status Badges
    statusNew: "नया समस्या",
    statusUnderReview: "जांच चल रहल हे",
    statusAssigned: "यूनिवर्सिटी मिलल",
    statusInProgress: "काम चल रहल हे",
    statusFunded: "अनुदान पास भेल",
    statusResolved: "हल भेल व जांचल",
    priorityHigh: "भारी जरूरी",
    priorityMedium: "मध्यम जरूरी",
    priorityLow: "साधारण",
  },
};

export const useLanguageStore = create((set, get) => ({
  language: localStorage.getItem("sahayog_lang") || "en",
  setLanguage: (lang) => {
    localStorage.setItem("sahayog_lang", lang);
    set({ language: lang });
  },
  t: (key) => {
    const lang = get().language;
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
  },
}));
