import { create } from "zustand";

export const TRANSLATIONS = {
  en: {
    // TopBar & Header
    searchPlaceholder: "Search issues, research projects, universities, CSR partners...",
    liveNotifications: "Live Notifications",
    markAllRead: "Mark all read",
    noNotifications: "No new notifications.",
    viewProgressTracker: "View Progress Tracker →",
    signOut: "Sign out",
    language: "Language",
    signedInAs: "Signed in as",
    role: "Role",
    organization: "Organization",
    district: "District",
    
    // Roles
    citizen: "Citizen",
    university: "University / HEI",
    industry: "Industry Partner",
    admin: "Admin / State Oversight",

    // Navigation & Sidebar
    portalBrand: "Sahayog",
    portalSubtitle: "Societal Innovation Portal",
    navReportIssue: "Report Challenge",
    navMyIssues: "My Challenges",
    navCampusQueue: "Campus Triage Queue",
    navProjects: "Research Projects",
    navCsrQueue: "CSR Proposals Queue",
    navFundedProjects: "Funded Projects",
    navAdminAnalytics: "Statewide Analytics",
    navVerifyAccounts: "Verify Accounts",
    networkOverview: "Sahayog Network",
    networkActive: "Active",

    // Landing Page
    heroBadge: "AI-Powered Societal Innovation Platform",
    heroTitlePre: "Connecting Community Challenges with ",
    heroTitleHighlight: "Universities & Industry",
    heroSubtitle: "Citizens report grassroots civic issues with a brief summary & photo. Our AI Engine formulates structured problem statements and computes severity scores, auto-routing them to the nearest universities to form multidisciplinary research teams funded by industry partners with tracked milestones.",
    reportCivicBtn: "Report a Civic Issue",
    loginBtn: "University / Industry Login",
    signIn: "Sign in",
    joinNetwork: "Join Network",
    heroCheck1: "AI Problem Structuring",
    heroCheck2: "Proximity Haversine Routing",
    heroCheck3: "Real-time Citizen Notification",
    liveActivity: "Live Platform Activity",
    liveActivitySample: "Fluoride Defluoridation Pilot funded by Tata Steel CSR",
    liveActivitySampleSub: "Assigned to BIT Mesra · Nearest campus (12.4 km) · 60-day completion deadline",
    howItWorks: "How Sahayog Works",
    fromReportToResolution: "From Citizen Report to Ground Resolution",
    workflowStep1Title: "1. Citizen Reporting",
    workflowStep1Desc: "Citizens describe local issues with a brief summary, photo, and geolocation coordinates.",
    workflowStep2Title: "2. AI Formulation & Routing",
    workflowStep2Desc: "AI crafts a structured research problem statement, evaluates multi-factor severity, and routes to nearest universities.",
    workflowStep3Title: "3. University Solutions",
    workflowStep3Desc: "Faculty and students build multidisciplinary teams, design engineering prototypes, and submit solution proposals.",
    workflowStep4Title: "4. Industry Funding & Closure",
    workflowStep4Desc: "Industries sponsor proposals, set completion deadlines, track milestones, and the citizen is notified upon resolution.",
    platformImpactDashboard: "Platform Impact Dashboard",
    realtimeIndicators: "Real-time indicators across districts",
    viewFullAnalytics: "View full analytics →",
    copyrightFooter: "© 2026 Sahayog — Societal Innovation Collaboration Platform. All rights reserved.",
    collabCivicSolving: "Collaborative Civic Problem Solving",

    // Auth (Login & Signup)
    welcomeBack: "Welcome to Sahayog",
    signInWorkspace: "Sign in to your collaboration workspace.",
    continueGoogle: "Continue with Google",
    continueCredentials: "or continue with credentials",
    quickDemoSwitcher: "Quick Demo Account Switcher:",
    emailAddress: "Email address",
    password: "Password",
    signInToDashboard: "Sign in to Dashboard",
    signingIn: "Signing in...",
    newToSahayog: "New to Sahayog?",
    createAnAccount: "Create an account",
    alreadyHaveAccount: "Already have an account?",
    joinSahayogNetwork: "Join Sahayog Network",
    fullName: "Full Name",
    selectRole: "Select Your Role",
    institutionName: "University / Industry Name",
    department: "Department / CSR Wing",

    // Report Issue Wizard
    reportTitle: "Report a Civic Challenge",
    reportSubtitle: "Tell us the problem briefly with a photo. Our AI Engine formulates the research problem statement & severity for nearest universities.",
    stepBasic: "Basic Info",
    stepDesc: "Short Description",
    stepPhoto: "Photo Evidence",
    stepLocation: "Location",
    stepReview: "AI Formulation & Review",
    issueTitleLabel: "Short Issue Title",
    issueTitlePlaceholder: "e.g. Broken storm drain flooding Albert Ekka Chowk",
    categoryLabel: "Initial Category",
    selectCategory: "Select Domain Category",
    descLabel: "Brief Problem Description",
    descPlaceholder: "e.g. During monsoon, the drain overflows onto the main commercial stretch for over 300 meters...",
    descTip: "Tip: Keep it concise! Mention who is affected, key hazard details, and duration. The Sahayog AI model will automatically synthesize a formal, comprehensive problem statement for university researchers.",
    photoLabel: "Upload Photo / Evidence",
    photoSubtitle: "Visual evidence feeds the AI severity analysis to compute flooding risk, structural hazard, and urgency score.",
    districtLabel: "District (Jharkhand)",
    blockLabel: "Block / Municipality",
    blockPlaceholder: "e.g. Kanke / Tamar / Jamshedpur Urban",
    landmarkLabel: "Landmark / Street Address",
    landmarkPlaceholder: "e.g. Near Albert Ekka Chowk",
    pinLocationMap: "Pin Location on Map (For Nearest University Distance Calculation)",
    useGps: "Use current GPS location",
    aiSynthesizing: "Synthesizing AI problem statement...",
    aiFormulatedTitle: "AI-Formulated Problem Statement & Severity",
    regenerateAi: "Regenerate AI",
    publicRisk: "Public Risk",
    urgencyLevel: "Urgency Level",
    compositeScore: "Composite Score",
    backBtn: "Back",
    continueBtn: "Continue",
    submitBtn: "Submit to Nearest Universities",
    submittingBtn: "Publishing to Sahayog Network...",

    // My Reported Challenges
    myReportedChallenges: "My Reported Challenges",
    myReportedSubtitle: "Track problem evaluation, university team assignments, industry funding, and resolution milestones.",
    reportNewChallenge: "Report New Issue",
    noReportedIssues: "You have not reported any civic challenges yet.",
    noReportedHelper: "Report a local issue in your district with photo and location to activate AI problem formulation and route it to nearest universities.",

    // Issue Detail
    citizenDescription: "Citizen Description",
    aiSynthesizedTitle: "AI-Synthesized Problem Statement",
    evidencePhotos: "Photo Evidence & Uploads",
    nearestRoutingTitle: "Nearest Universities & Distance Routing",
    assembleTeamTitle: "Assemble Multidisciplinary Team",
    assembleTeamSubtitle: "Constitute student and faculty teams across disciplines to prepare the solution proposal.",
    saveTeamDraftProposal: "Save Team & Draft Proposal",
    exportCsrCert: "CSR Impact Certificate",
    claimChallenge: "Claim for University",
    claiming: "Claiming...",
    nearestCampus: "Nearest Campus",
    kmFromCampus: "km from campus",
    priority1: "Priority 1",
    priority2: "Priority 2",

    // Progress Tracker
    trackerTitle: "Live Ticket Progress Tracker",
    trackerSubtitle: "Real-time Amazon-style delivery tracker for citizen resolution",
    stageReported: "Reported & AI Assessed",
    stageAssigned: "University Team Formed",
    stageFunded: "Proposal & CSR Funded",
    stageExecution: "Field Execution & Milestones",
    stageResolved: "Resolved & Verified",
    stageCompleted: "Completed",
    stageInProgress: "In Progress",
    stageUpcoming: "Upcoming",
    liveActivityFeed: "Live Activity Stream & Milestone Audit Feed",
    overallResolution: "Overall Resolution",

    // Citizen Feedback & Verification
    feedbackTitle: "Citizen Resolution Verification & Rating",
    feedbackSubtitle: "Please verify on-ground satisfaction and rate the innovation team's solution.",
    rateSolution: "Rate the Quality & Speed of Resolution:",
    feedbackPlaceholder: "Tell the community and state innovation council about the impact (e.g. Water is clean and flowing now!)...",
    verifyGroundCheck: "I verify that this civic challenge has been physically resolved on the ground.",
    submitFeedbackBtn: "Submit Citizen Verification & Rating",
    verifiedByCitizenBadge: "Verified by Citizen Reporter",
    citizenRatingLabel: "Citizen Satisfaction Score",
    thankYouFeedback: "Thank you for verifying and rating this civic innovation project!",

    // Status Badges
    statusNew: "New",
    statusUnderReview: "Under review",
    statusAssigned: "Assigned",
    statusInProgress: "In progress",
    statusFunded: "Funded",
    statusResolved: "Resolved",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
  },

  hi: {
    // TopBar & Header
    searchPlaceholder: "समस्याएं, शोध परियोजनाएं, विश्वविद्यालय, सीएसआर भागीदार खोजें...",
    liveNotifications: "ताज़ा सूचनाएं",
    markAllRead: "सभी पढ़ी गई चिह्नित करें",
    noNotifications: "कोई नई सूचना नहीं।",
    viewProgressTracker: "प्रगति ट्रैकर देखें →",
    signOut: "लॉग आउट करें",
    language: "भाषा",
    signedInAs: "लॉग इन उपयोगकर्ता",
    role: "भूमिका",
    organization: "संस्थान / संगठन",
    district: "जिला",

    // Roles
    citizen: "नागरिक",
    university: "विश्वविद्यालय / संस्थान",
    industry: "उद्योग / CSR भागीदार",
    admin: "राज्य प्रशासन / इनोवेशन काउंसिल",

    // Navigation & Sidebar
    portalBrand: "सहयोग",
    portalSubtitle: "सामाजिक नवाचार पोर्टल",
    navReportIssue: "समस्या दर्ज करें",
    navMyIssues: "मेरी समस्याएं",
    navCampusQueue: "विश्वविद्यालय कतार",
    navProjects: "शोध परियोजनाएं",
    navCsrQueue: "CSR अनुदान प्रस्ताव",
    navFundedProjects: "स्वीकृत परियोजनाएं",
    navAdminAnalytics: "राज्य स्तरीय विश्लेषण",
    navVerifyAccounts: "खाता सत्यापन",
    networkOverview: "सहयोग नेटवर्क",
    networkActive: "सक्रिय",

    // Landing Page
    heroBadge: "AI-संचालित सामाजिक नवाचार मंच",
    heroTitlePre: "नागरिक समस्याओं को जोड़ना ",
    heroTitleHighlight: "विश्वविद्यालयों और उद्योग जगत से",
    heroSubtitle: "नागरिक फोटो और संक्षिप्त विवरण के साथ जमीनी समस्याएं दर्ज करते हैं। हमारा AI इंजन औपचारिक शोध समस्या विवरण तैयार कर नजदीकी विश्वविद्यालयों को भेजता है, जहां बहुविषयक टीमें उद्योग सीएसआर फंडिंग से समाधान बनाती हैं।",
    reportCivicBtn: "नागरिक समस्या दर्ज करें",
    loginBtn: "विश्वविद्यालय / उद्योग लॉगिन",
    signIn: "लॉगिन करें",
    joinNetwork: "नेटवर्क से जुड़ें",
    heroCheck1: "AI समस्या सूत्रीकरण",
    heroCheck2: "निकटतम विश्वविद्यालय रूटिंग",
    heroCheck3: "नागरिकों को रीयल-टाइम सूचना",
    liveActivity: "मंच की लाइव गतिविधि",
    liveActivitySample: "टाटा स्टील सीएसआर द्वारा वित्तपोषित फ्लोराइड शुद्धिकरण पायलट",
    liveActivitySampleSub: "बीआईटी मेसरा को आवंटित · निकटतम परिसर (12.4 किमी) · 60 दिन की समयसीमा",
    howItWorks: "सहयोग कैसे काम करता है",
    fromReportToResolution: "नागरिक रिपोर्ट से लेकर जमीनी समाधान तक",
    workflowStep1Title: "1. नागरिक रिपोर्टिंग",
    workflowStep1Desc: "नागरिक संक्षिप्त विवरण, फोटो और स्थान के साथ स्थानीय समस्या दर्ज करते हैं।",
    workflowStep2Title: "2. AI विश्लेषण और रूटिंग",
    workflowStep2Desc: "AI औपचारिक समस्या विवरण तैयार कर गंभीरता आंकता है और नजदीकी विश्वविद्यालयों को भेजता है।",
    workflowStep3Title: "3. विश्वविद्यालय समाधान",
    workflowStep3Desc: "प्रोफेसर और छात्र बहुविषयक टीमें बनाकर प्रोटोटाइप तैयार करते हैं और प्रस्ताव भेजते हैं।",
    workflowStep4Title: "4. उद्योग फंडिंग और समाधान",
    workflowStep4Desc: "उद्योग CSR से अनुदान देते हैं, माइलस्टोन ट्रैक करते हैं और समाधान होने पर नागरिक को सूचना मिलती है।",
    platformImpactDashboard: "मंच प्रभाव डैशबोर्ड",
    realtimeIndicators: "जिलों में रीयल-टाइम आंकड़े",
    viewFullAnalytics: "पूर्ण विश्लेषण देखें →",
    copyrightFooter: "© 2026 सहयोग — सामाजिक नवाचार सहभागिता मंच। सर्वाधिकार सुरक्षित।",
    collabCivicSolving: "सहयोगात्मक नागरिक समस्या समाधान",

    // Auth (Login & Signup)
    welcomeBack: "सहयोग में आपका स्वागत है",
    signInWorkspace: "अपने सहभागिता डैशबोर्ड में लॉगिन करें।",
    continueGoogle: "Google के साथ जारी रखें",
    continueCredentials: "या ईमेल और पासवर्ड से जारी रखें",
    quickDemoSwitcher: "त्वरित डेमो खाता चयनकर्ता:",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    signInToDashboard: "डैशबोर्ड में लॉगिन करें",
    signingIn: "लॉगिन हो रहा है...",
    newToSahayog: "सहयोग पर नए हैं?",
    createAnAccount: "नया खाता बनाएं",
    alreadyHaveAccount: "क्या आपके पास पहले से खाता है?",
    joinSahayogNetwork: "सहयोग नेटवर्क से जुड़ें",
    fullName: "पूरा नाम",
    selectRole: "अपनी भूमिका चुनें",
    institutionName: "विश्वविद्यालय / उद्योग का नाम",
    department: "विभाग / सीएसआर शाखा",

    // Report Issue Wizard
    reportTitle: "नागरिक समस्या दर्ज करें",
    reportSubtitle: "फोटो और संक्षिप्त विवरण दें। हमारा AI इंजन समस्या का शोध विवरण तैयार कर नजदीकी विश्वविद्यालय को भेजेगा।",
    stepBasic: "मूल जानकारी",
    stepDesc: "समस्या विवरण",
    stepPhoto: "फोटो प्रमाण",
    stepLocation: "स्थान",
    stepReview: "AI विश्लेषण और समीक्षा",
    issueTitleLabel: "समस्या का शीर्षक",
    issueTitlePlaceholder: "उदा. अल्बर्ट एक्का चौक पर जलभराव और नाली जाम",
    categoryLabel: "समस्या की श्रेणी",
    selectCategory: "श्रेणी चुनें",
    descLabel: "समस्या का संक्षिप्त विवरण",
    descPlaceholder: "उदा. बारिश में नाला सड़क पर बहने लगता है, जिससे 300 मीटर तक आवागमन बंद हो जाता है...",
    descTip: "सुझाव: विवरण संक्षिप्त रखें! प्रभावित लोगों, मुख्य खतरे और अवधि का उल्लेख करें। सहयोग AI मॉडल शोधकर्ताओं के लिए औपचारिक समस्या विवरण तैयार करेगा।",
    photoLabel: "फोटो / प्रमाण अपलोड करें",
    photoSubtitle: "फोटो से AI बाढ़ जोखिम, सुरक्षा खतरा और तात्कालिकता स्कोर की गणना करता है।",
    districtLabel: "जिला (झारखंड)",
    blockLabel: "प्रखंड / नगर निकाय",
    blockPlaceholder: "उदा. कांके / तमाड़ / जमशेदपुर",
    landmarkLabel: "लैंडमार्क / सड़क का नाम",
    landmarkPlaceholder: "उदा. अल्बर्ट एक्का चौक के पास",
    pinLocationMap: "नक्शे पर सटीक स्थान चुनें (विश्वविद्यालय दूरी गणना हेतु)",
    useGps: "वर्तमान GPS स्थान का उपयोग करें",
    aiSynthesizing: "AI शोध विवरण तैयार किया जा रहा है...",
    aiFormulatedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या और गंभीरता",
    regenerateAi: "पुनः AI बनाएं",
    publicRisk: "सार्वजनिक जोखिम",
    urgencyLevel: "तात्कालिकता",
    compositeScore: "कुल गंभीरता स्कोर",
    backBtn: "पीछे",
    continueBtn: "आगे बढ़ें",
    submitBtn: "नजदीकी विश्वविद्यालयों को भेजें",
    submittingBtn: "सहयोग नेटवर्क पर प्रकाशित हो रहा है...",

    // My Reported Challenges
    myReportedChallenges: "मेरी दर्ज की गई समस्याएं",
    myReportedSubtitle: "समस्या मूल्यांकन, विश्वविद्यालय टीम गठन, उद्योग फंडिंग और समाधान माइलस्टोन को ट्रैक करें।",
    reportNewChallenge: "नई समस्या दर्ज करें",
    noReportedIssues: "आपने अभी तक कोई नागरिक समस्या दर्ज नहीं की है।",
    noReportedHelper: "AI विश्लेषण शुरू करने और नजदीकी विश्वविद्यालयों तक पहुंचाने के लिए अपने जिले की समस्या फोटो सहित दर्ज करें।",

    // Issue Detail
    citizenDescription: "नागरिक द्वारा दिया गया विवरण",
    aiSynthesizedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या",
    evidencePhotos: "फोटो प्रमाण व अपलोड",
    nearestRoutingTitle: "नजदीकी विश्वविद्यालय और दूरी रूटिंग",
    assembleTeamTitle: "बहुविषयक अनुसंधान टीम गठित करें",
    assembleTeamSubtitle: "समाधान प्रस्ताव तैयार करने के लिए विभिन्न विभागों के छात्रों और प्रोफेसरों की टीम बनाएं।",
    saveTeamDraftProposal: "टीम सुरक्षित करें और प्रस्ताव बनाएं",
    exportCsrCert: "CSR इम्पैक्ट प्रमाणपत्र",
    claimChallenge: "विश्वविद्यालय के लिए दावा करें",
    claiming: "दावा दर्ज हो रहा है...",
    nearestCampus: "निकटतम परिसर",
    kmFromCampus: "किमी परिसर से दूर",
    priority1: "प्राथमिकता 1",
    priority2: "प्राथमिकता 2",

    // Progress Tracker
    trackerTitle: "लाइव समस्या प्रगति ट्रैकर",
    trackerSubtitle: "नागरिक समाधान के लिए रीयल-टाइम अमेज़न-स्टाइल डिलीवरी ट्रैकर",
    stageReported: "दर्ज व AI मूल्यांकित",
    stageAssigned: "विश्वविद्यालय टीम गठित",
    stageFunded: "प्रस्ताव व CSR अनुदान स्वीकृत",
    stageExecution: "मैदानी क्रियान्वयन व माइलस्टोन",
    stageResolved: "समाधान संपन्न व सत्यापित",
    stageCompleted: "पूर्ण",
    stageInProgress: "प्रगति पर",
    stageUpcoming: "आगामी",
    liveActivityFeed: "लाइव गतिविधि व माइलस्टोन ऑडिट फ़ीड",
    overallResolution: "कुल समाधान प्रगति",

    // Citizen Feedback & Verification
    feedbackTitle: "नागरिक समाधान सत्यापन और रेटिंग",
    feedbackSubtitle: "कृपया जमीनी समाधान की पुष्टि करें और विश्वविद्यालय टीम के कार्य को रेट करें।",
    rateSolution: "समाधान की गुणवत्ता और गति को स्टार दें:",
    feedbackPlaceholder: "समुदाय और राज्य परिषद को जमीनी प्रभाव बताएं (उदा. पानी अब पूरी तरह साफ और उपलब्ध है!)...",
    verifyGroundCheck: "मैं पुष्टि करता हूँ कि यह नागरिक समस्या जमीन पर सफलतापूर्वक हल हो चुकी है।",
    submitFeedbackBtn: "नागरिक सत्यापन और रेटिंग जमा करें",
    verifiedByCitizenBadge: "नागरिक द्वारा सत्यापित",
    citizenRatingLabel: "नागरिक संतुष्टि स्कोर",
    thankYouFeedback: "सत्यापन और रेटिंग देने के लिए धन्यवाद!",

    // Status Badges
    statusNew: "नई समस्या",
    statusUnderReview: "समीक्षाधीन",
    statusAssigned: "विश्वविद्यालय आवंटित",
    statusInProgress: "प्रगति पर",
    statusFunded: "अनुदान स्वीकृत",
    statusResolved: "हल व सत्यापित",
    priorityHigh: "उच्च प्राथमिकता",
    priorityMedium: "मध्यम प्राथमिकता",
    priorityLow: "सामान्य प्राथमिकता",
  },
};

export const useLanguageStore = create((set, get) => ({
  language: localStorage.getItem("sahayog_lang") || "en",
  setLanguage: (lang) => {
    localStorage.setItem("sahayog_lang", lang);
    set({ language: lang });
  },
  t: (key) => {
    const lang = get().language;
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
  },
}));
