import { create } from "zustand";

export const TRANSLATIONS = {
  en: {
    // TopBar & Header
    searchPlaceholder: "Search issues, research projects, universities, CSR partners...",
    liveNotifications: "Live Notifications",
    markAllRead: "Mark all read",
    noNotifications: "No new notifications.",
    viewProgressTracker: "View Progress Tracker →",
    signOut: "Sign out",
    language: "Language",
    signedInAs: "Signed in as",
    role: "Role",
    organization: "Organization",
    district: "District",
    
    // Roles
    citizen: "Citizen",
    university: "University / HEI",
    industry: "Industry Partner",
    admin: "Admin / State Oversight",

    // Navigation & Sidebar
    portalBrand: "Sahayog",
    portalSubtitle: "Societal Innovation Portal",
    navReportIssue: "Report Challenge",
    navMyIssues: "My Challenges",
    navCampusQueue: "Campus Triage Queue",
    navProjects: "Research Projects",
    navCsrQueue: "CSR Proposals Queue",
    navFundedProjects: "Funded Projects",
    navAdminAnalytics: "Statewide Analytics",
    navVerifyAccounts: "Verify Accounts",
    networkOverview: "Sahayog Network",
    networkActive: "Active",

    // Landing Page
    heroBadge: "AI-Powered Societal Innovation Platform",
    heroTitlePre: "Connecting Community Challenges with ",
    heroTitleHighlight: "Universities & Industry",
    heroSubtitle: "Citizens report grassroots civic issues with a brief summary & photo. Our AI Engine formulates structured problem statements and computes severity scores, auto-routing them to the nearest universities to form multidisciplinary research teams funded by industry partners with tracked milestones.",
    reportCivicBtn: "Report a Civic Issue",
    loginBtn: "University / Industry Login",
    signIn: "Sign in",
    joinNetwork: "Join Network",
    heroCheck1: "AI Problem Structuring",
    heroCheck2: "Proximity Haversine Routing",
    heroCheck3: "Real-time Citizen Notification",
    liveActivity: "Live Platform Activity",
    liveActivitySample: "Fluoride Defluoridation Pilot funded by Tata Steel CSR",
    liveActivitySampleSub: "Assigned to BIT Mesra · Nearest campus (12.4 km) · 60-day completion deadline",
    howItWorks: "How Sahayog Works",
    fromReportToResolution: "From Citizen Report to Ground Resolution",
    workflowStep1Title: "1. Citizen Reporting",
    workflowStep1Desc: "Citizens describe local issues with a brief summary, photo, and geolocation coordinates.",
    workflowStep2Title: "2. AI Formulation & Routing",
    workflowStep2Desc: "AI crafts a structured research problem statement, evaluates multi-factor severity, and routes to nearest universities.",
    workflowStep3Title: "3. University Solutions",
    workflowStep3Desc: "Faculty and students build multidisciplinary teams, design engineering prototypes, and submit solution proposals.",
    workflowStep4Title: "4. Industry Funding & Closure",
    workflowStep4Desc: "Industries sponsor proposals, set completion deadlines, track milestones, and the citizen is notified upon resolution.",
    platformImpactDashboard: "Platform Impact Dashboard",
    realtimeIndicators: "Real-time indicators across districts",
    viewFullAnalytics: "View full analytics →",
    copyrightFooter: "© 2026 Sahayog — Societal Innovation Collaboration Platform. All rights reserved.",
    collabCivicSolving: "Collaborative Civic Problem Solving",

    // Auth (Login & Signup)
    welcomeBack: "Welcome to Sahayog",
    signInWorkspace: "Sign in to your collaboration workspace.",
    continueGoogle: "Continue with Google",
    continueCredentials: "or continue with credentials",
    quickDemoSwitcher: "Quick Demo Account Switcher:",
    emailAddress: "Email address",
    password: "Password",
    signInToDashboard: "Sign in to Dashboard",
    signingIn: "Signing in...",
    newToSahayog: "New to Sahayog?",
    createAnAccount: "Create an account",
    alreadyHaveAccount: "Already have an account?",
    joinSahayogNetwork: "Join Sahayog Network",
    fullName: "Full Name",
    selectRole: "Select Your Role",
    institutionName: "University / Industry Name",
    department: "Department / CSR Wing",

    // Report Issue Wizard
    reportTitle: "Report a Civic Challenge",
    reportSubtitle: "Tell us the problem briefly with a photo. Our AI Engine formulates the research problem statement & severity for nearest universities.",
    stepBasic: "Basic Info",
    stepDesc: "Short Description",
    stepPhoto: "Photo Evidence",
    stepLocation: "Location",
    stepReview: "AI Formulation & Review",
    issueTitleLabel: "Short Issue Title",
    issueTitlePlaceholder: "e.g. Broken storm drain flooding Albert Ekka Chowk",
    categoryLabel: "Initial Category",
    selectCategory: "Select Domain Category",
    descLabel: "Brief Problem Description",
    descPlaceholder: "e.g. During monsoon, the drain overflows onto the main commercial stretch for over 300 meters...",
    descTip: "Tip: Keep it concise! Mention who is affected, key hazard details, and duration. The Sahayog AI model will automatically synthesize a formal, comprehensive problem statement for university researchers.",
    photoLabel: "Upload Photo / Evidence",
    photoSubtitle: "Visual evidence feeds the AI severity analysis to compute flooding risk, structural hazard, and urgency score.",
    districtLabel: "District (Jharkhand)",
    blockLabel: "Block / Municipality",
    blockPlaceholder: "e.g. Kanke / Tamar / Jamshedpur Urban",
    landmarkLabel: "Landmark / Street Address",
    landmarkPlaceholder: "e.g. Near Albert Ekka Chowk",
    pinLocationMap: "Pin Location on Map (For Nearest University Distance Calculation)",
    useGps: "Use current GPS location",
    aiSynthesizing: "Synthesizing AI problem statement...",
    aiFormulatedTitle: "AI-Formulated Problem Statement & Severity",
    regenerateAi: "Regenerate AI",
    publicRisk: "Public Risk",
    floodRisk: "Flood Risk",
    urgencyLevel: "Urgency Level",
    compositeScore: "Composite Score",
    issueLoadFailed: "Failed to load this issue. Please try again.",
    retryBtn: "Retry",
    backBtn: "Back",
    continueBtn: "Continue",
    submitBtn: "Submit to Nearest Universities",
    submittingBtn: "Publishing to Sahayog Network...",

    // My Reported Challenges
    myReportedChallenges: "My Reported Challenges",
    myReportedSubtitle: "Track problem evaluation, university team assignments, industry funding, and resolution milestones.",
    reportNewChallenge: "Report New Issue",
    noReportedIssues: "You have not reported any civic challenges yet.",
    noReportedHelper: "Report a local issue in your district with photo and location to activate AI problem formulation and route it to nearest universities.",

    // Issue Detail
    citizenDescription: "Citizen Description",
    aiSynthesizedTitle: "AI-Synthesized Problem Statement",
    evidencePhotos: "Photo Evidence & Uploads",
    nearestRoutingTitle: "Nearest Universities & Distance Routing",
    assembleTeamTitle: "Assemble Multidisciplinary Team",
    assembleTeamSubtitle: "Constitute student and faculty teams across disciplines to prepare the solution proposal.",
    saveTeamDraftProposal: "Save Team & Draft Proposal",
    exportCsrCert: "CSR Impact Certificate",
    claimChallenge: "Claim for University",
    claiming: "Claiming...",
    nearestCampus: "Nearest Campus",
    kmFromCampus: "km from campus",
    priority1: "Priority 1",
    priority2: "Priority 2",

    // Progress Tracker
    trackerTitle: "Live Ticket Progress Tracker",
    trackerSubtitle: "Real-time Amazon-style delivery tracker for citizen resolution",
    stageReported: "Reported & AI Assessed",
    stageAssigned: "University Team Formed",
    stageFunded: "Proposal & CSR Funded",
    stageExecution: "Field Execution & Milestones",
    stageResolved: "Resolved & Verified",
    stageCompleted: "Completed",
    stageInProgress: "In Progress",
    stageUpcoming: "Upcoming",
    liveActivityFeed: "Live Activity Stream & Milestone Audit Feed",
    overallResolution: "Overall Resolution",

    // Citizen Feedback & Verification
    feedbackTitle: "Citizen Resolution Verification & Rating",
    feedbackSubtitle: "Please verify on-ground satisfaction and rate the innovation team's solution.",
    rateSolution: "Rate the Quality & Speed of Resolution:",
    feedbackPlaceholder: "Tell the community and state innovation council about the impact (e.g. Water is clean and flowing now!)...",
    verifyGroundCheck: "I verify that this civic challenge has been physically resolved on the ground.",
    submitFeedbackBtn: "Submit Citizen Verification & Rating",
    verifiedByCitizenBadge: "Verified by Citizen Reporter",
    citizenRatingLabel: "Citizen Satisfaction Score",
    thankYouFeedback: "Thank you for verifying and rating this civic innovation project!",

    // University Pages
    uniDashboardTitle: "University Research & Innovation Hub",
    uniDashboardSubtitle: "Triage localized civic problems, assemble multidisciplinary student/faculty teams, and draft research proposals.",
    claimBtn: "Claim Challenge",
    claimedBadge: "Claimed by Campus",
    pendingProposals: "Proposals Awaiting CSR",
    activeProjectsCount: "Active Engineering Pilots",
    assignedQueueTitle: "Incoming Campus Triage Queue",

    // Industry Pages
    industryQueueTitle: "CSR Societal Innovation Queue",
    industryQueueSubtitle: "Review university research proposals, evaluate budget milestones, and allocate CSR grants for localized impact.",
    sponsorProposalBtn: "Sponsor & Fund Project",
    fundingAllocated: "Total CSR Grants Deployed",
    fundedProjectsTitle: "Industry Sponsored Projects",
    fundedProjectsSubtitle: "Monitor milestone deliverables, deadlines, and social impact of funded innovation projects.",

    // Admin Pages
    adminDashboardTitle: "Statewide Innovation Command Center",
    adminDashboardSubtitle: "Real-time oversight of problem routing, HEI engagement, CSR grant allocation, and civic resolution velocity.",
    verifyAccountsTitle: "Institution & User Verification",
    verifyAccountsSubtitle: "Audit credentials and authorize Higher Education Institutions and Corporate CSR entities.",

    // Status Badges
    statusNew: "New",
    statusUnderReview: "Under review",
    statusAssigned: "Assigned",
    statusInProgress: "In progress",
    statusFunded: "Funded",
    statusResolved: "Resolved",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
  },

  hi: {
    // TopBar & Header
    searchPlaceholder: "समस्याएं, शोध परियोजनाएं, विश्वविद्यालय, सीएसआर भागीदार खोजें...",
    liveNotifications: "ताज़ा सूचनाएं",
    markAllRead: "सभी पढ़ी गई चिह्नित करें",
    noNotifications: "कोई नई सूचना नहीं।",
    viewProgressTracker: "प्रगति ट्रैकर देखें →",
    signOut: "लॉग आउट करें",
    language: "भाषा",
    signedInAs: "लॉग इन उपयोगकर्ता",
    role: "भूमिका",
    organization: "संस्थान / संगठन",
    district: "जिला",

    // Roles
    citizen: "नागरिक",
    university: "विश्वविद्यालय / संस्थान",
    industry: "उद्योग / CSR भागीदार",
    admin: "राज्य प्रशासन / इनोवेशन काउंसिल",

    // Navigation & Sidebar
    portalBrand: "सहयोग",
    portalSubtitle: "सामाजिक नवाचार पोर्टल",
    navReportIssue: "समस्या दर्ज करें",
    navMyIssues: "मेरी समस्याएं",
    navCampusQueue: "विश्वविद्यालय कतार",
    navProjects: "शोध परियोजनाएं",
    navCsrQueue: "CSR अनुदान प्रस्ताव",
    navFundedProjects: "स्वीकृत परियोजनाएं",
    navAdminAnalytics: "राज्य स्तरीय विश्लेषण",
    navVerifyAccounts: "खाता सत्यापन",
    networkOverview: "सहयोग नेटवर्क",
    networkActive: "सक्रिय",

    // Landing Page
    heroBadge: "AI-संचालित सामाजिक नवाचार मंच",
    heroTitlePre: "नागरिक समस्याओं को जोड़ना ",
    heroTitleHighlight: "विश्वविद्यालयों और उद्योग जगत से",
    heroSubtitle: "नागरिक फोटो और संक्षिप्त विवरण के साथ जमीनी समस्याएं दर्ज करते हैं। हमारा AI इंजन औपचारिक शोध समस्या विवरण तैयार कर नजदीकी विश्वविद्यालयों को भेजता है, जहां बहुविषयक टीमें उद्योग सीएसआर फंडिंग से समाधान बनाती हैं।",
    reportCivicBtn: "नागरिक समस्या दर्ज करें",
    loginBtn: "विश्वविद्यालय / उद्योग लॉगिन",
    signIn: "लॉगिन करें",
    joinNetwork: "नेटवर्क से जुड़ें",
    heroCheck1: "AI समस्या सूत्रीकरण",
    heroCheck2: "निकटतम विश्वविद्यालय रूटिंग",
    heroCheck3: "नागरिकों को रीयल-टाइम सूचना",
    liveActivity: "मंच की लाइव गतिविधि",
    liveActivitySample: "टाटा स्टील सीएसआर द्वारा वित्तपोषित फ्लोराइड शुद्धिकरण पायलट",
    liveActivitySampleSub: "बीआईटी मेसरा को आवंटित · निकटतम परिसर (12.4 किमी) · 60 दिन की समयसीमा",
    howItWorks: "सहयोग कैसे काम करता है",
    fromReportToResolution: "नागरिक रिपोर्ट से लेकर जमीनी समाधान तक",
    workflowStep1Title: "1. नागरिक रिपोर्टिंग",
    workflowStep1Desc: "नागरिक संक्षिप्त विवरण, फोटो और स्थान के साथ स्थानीय समस्या दर्ज करते हैं।",
    workflowStep2Title: "2. AI विश्लेषण और रूटिंग",
    workflowStep2Desc: "AI औपचारिक समस्या विवरण तैयार कर गंभीरता आंकता है और नजदीकी विश्वविद्यालयों को भेजता है।",
    workflowStep3Title: "3. विश्वविद्यालय समाधान",
    workflowStep3Desc: "प्रोफेसर और छात्र बहुविषयक टीमें बनाकर प्रोटोटाइप तैयार करते हैं और प्रस्ताव भेजते हैं।",
    workflowStep4Title: "4. उद्योग फंडिंग और समाधान",
    workflowStep4Desc: "उद्योग CSR से अनुदान देते हैं, माइलस्टोन ट्रैक करते हैं और समाधान होने पर नागरिक को सूचना मिलती है।",
    platformImpactDashboard: "मंच प्रभाव डैशबोर्ड",
    realtimeIndicators: "जिलों में रीयल-टाइम आंकड़े",
    viewFullAnalytics: "पूर्ण विश्लेषण देखें →",
    copyrightFooter: "© 2026 सहयोग — सामाजिक नवाचार सहभागिता मंच। सर्वाधिकार सुरक्षित।",
    collabCivicSolving: "सहयोगात्मक नागरिक समस्या समाधान",

    // Auth (Login & Signup)
    welcomeBack: "सहयोग में आपका स्वागत है",
    signInWorkspace: "अपने सहभागिता डैशबोर्ड में लॉगिन करें।",
    continueGoogle: "Google के साथ जारी रखें",
    continueCredentials: "या ईमेल और पासवर्ड से जारी रखें",
    quickDemoSwitcher: "त्वरित डेमो खाता चयनकर्ता:",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    signInToDashboard: "डैशबोर्ड में लॉगिन करें",
    signingIn: "लॉगिन हो रहा है...",
    newToSahayog: "सहयोग पर नए हैं?",
    createAnAccount: "नया खाता बनाएं",
    alreadyHaveAccount: "क्या आपके पास पहले से खाता है?",
    joinSahayogNetwork: "सहयोग नेटवर्क से जुड़ें",
    fullName: "पूरा नाम",
    selectRole: "अपनी भूमिका चुनें",
    institutionName: "विश्वविद्यालय / उद्योग का नाम",
    department: "विभाग / सीएसआर शाखा",

    // Report Issue Wizard
    reportTitle: "नागरिक समस्या दर्ज करें",
    reportSubtitle: "फोटो और संक्षिप्त विवरण दें। हमारा AI इंजन समस्या का शोध विवरण तैयार कर नजदीकी विश्वविद्यालय को भेजेगा।",
    stepBasic: "मूल जानकारी",
    stepDesc: "समस्या विवरण",
    stepPhoto: "फोटो प्रमाण",
    stepLocation: "स्थान",
    stepReview: "AI विश्लेषण और समीक्षा",
    issueTitleLabel: "समस्या का शीर्षक",
    issueTitlePlaceholder: "उदा. अल्बर्ट एक्का चौक पर जलभराव और नाली जाम",
    categoryLabel: "समस्या की श्रेणी",
    selectCategory: "श्रेणी चुनें",
    descLabel: "समस्या का संक्षिप्त विवरण",
    descPlaceholder: "उदा. बारिश में नाला सड़क पर बहने लगता है, जिससे 300 मीटर तक आवागमन बंद हो जाता है...",
    descTip: "सुझाव: विवरण संक्षिप्त रखें! प्रभावित लोगों, मुख्य खतरे और अवधि का उल्लेख करें। सहयोग AI मॉडल शोधकर्ताओं के लिए औपचारिक समस्या विवरण तैयार करेगा।",
    photoLabel: "फोटो / प्रमाण अपलोड करें",
    photoSubtitle: "फोटो से AI बाढ़ जोखिम, सुरक्षा खतरा और तात्कालिकता स्कोर की गणना करता है।",
    districtLabel: "जिला (झारखंड)",
    blockLabel: "प्रखंड / नगर निकाय",
    blockPlaceholder: "उदा. कांके / तमाड़ / जमशेदपुर",
    landmarkLabel: "लैंडमार्क / सड़क का नाम",
    landmarkPlaceholder: "उदा. अल्बर्ट एक्का चौक के पास",
    pinLocationMap: "नक्शे पर सटीक स्थान चुनें (विश्वविद्यालय दूरी गणना हेतु)",
    useGps: "वर्तमान GPS स्थान का उपयोग करें",
    aiSynthesizing: "AI शोध विवरण तैयार किया जा रहा है...",
    aiFormulatedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या और गंभीरता",
    regenerateAi: "पुनः AI बनाएं",
    publicRisk: "सार्वजनिक जोखिम",
    floodRisk: "बाढ़ जोखिम",
    urgencyLevel: "तात्कालिकता",
    compositeScore: "कुल गंभीरता स्कोर",
    backBtn: "पीछे",
    continueBtn: "आगे बढ़ें",
    submitBtn: "नजदीकी विश्वविद्यालयों को भेजें",
    submittingBtn: "सहयोग नेटवर्क पर प्रकाशित हो रहा है...",

    // My Reported Challenges
    myReportedChallenges: "मेरी दर्ज की गई समस्याएं",
    myReportedSubtitle: "समस्या मूल्यांकन, विश्वविद्यालय टीम गठन, उद्योग फंडिंग और समाधान माइलस्टोन को ट्रैक करें।",
    reportNewChallenge: "नई समस्या दर्ज करें",
    noReportedIssues: "आपने अभी तक कोई नागरिक समस्या दर्ज नहीं की है।",
    noReportedHelper: "AI विश्लेषण शुरू करने और नजदीकी विश्वविद्यालयों तक पहुंचाने के लिए अपने जिले की समस्या फोटो सहित दर्ज करें।",

    // Issue Detail
    citizenDescription: "नागरिक द्वारा दिया गया विवरण",
    aiSynthesizedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या",
    evidencePhotos: "फोटो प्रमाण व अपलोड",
    nearestRoutingTitle: "नजदीकी विश्वविद्यालय और दूरी रूटिंग",
    assembleTeamTitle: "बहुविषयक अनुसंधान टीम गठित करें",
    assembleTeamSubtitle: "समाधान प्रस्ताव तैयार करने के लिए विभिन्न विभागों के छात्रों और प्रोफेसरों की टीम बनाएं।",
    saveTeamDraftProposal: "टीम सुरक्षित करें और प्रस्ताव बनाएं",
    exportCsrCert: "CSR इम्पैक्ट प्रमाणपत्र",
    claimChallenge: "विश्वविद्यालय के लिए दावा करें",
    claiming: "दावा दर्ज हो रहा है...",
    nearestCampus: "निकटतम परिसर",
    kmFromCampus: "किमी परिसर से दूर",
    priority1: "प्राथमिकता 1",
    priority2: "प्राथमिकता 2",

    // Progress Tracker
    trackerTitle: "लाइव समस्या प्रगति ट्रैकर",
    trackerSubtitle: "नागरिक समाधान के लिए रीयल-टाइम अमेज़न-स्टाइल डिलीवरी ट्रैकर",
    stageReported: "दर्ज व AI मूल्यांकित",
    stageAssigned: "विश्वविद्यालय टीम गठित",
    stageFunded: "प्रस्ताव व CSR अनुदान स्वीकृत",
    stageExecution: "मैदानी क्रियान्वयन व माइलस्टोन",
    stageResolved: "समाधान संपन्न व सत्यापित",
    stageCompleted: "पूर्ण",
    stageInProgress: "प्रगति पर",
    stageUpcoming: "आगामी",
    liveActivityFeed: "लाइव गतिविधि व माइलस्टोन ऑडिट फ़ीड",
    overallResolution: "कुल समाधान प्रगति",

    // Citizen Feedback & Verification
    feedbackTitle: "नागरिक समाधान सत्यापन और रेटिंग",
    feedbackSubtitle: "कृपया जमीनी समाधान की पुष्टि करें और विश्वविद्यालय टीम के कार्य को रेट करें।",
    rateSolution: "समाधान की गुणवत्ता और गति को स्टार दें:",
    feedbackPlaceholder: "समुदाय और राज्य परिषद को जमीनी प्रभाव बताएं (उदा. पानी अब पूरी तरह साफ और उपलब्ध है!)...",
    verifyGroundCheck: "मैं पुष्टि करता हूँ कि यह नागरिक समस्या जमीन पर सफलतापूर्वक हल हो चुकी है।",
    submitFeedbackBtn: "नागरिक सत्यापन और रेटिंग जमा करें",
    verifiedByCitizenBadge: "नागरिक द्वारा सत्यापित",
    citizenRatingLabel: "नागरिक संतुष्टि स्कोर",
    thankYouFeedback: "सत्यापन और रेटिंग देने के लिए धन्यवाद!",

    // University Pages
    uniDashboardTitle: "विश्वविद्यालय अनुसंधान एवं नवाचार केंद्र",
    uniDashboardSubtitle: "स्थानीय समस्याओं की जांच करें, छात्रों और प्रोफेसरों की बहुविषयक टीम बनाएं और शोध प्रस्ताव तैयार करें।",
    claimBtn: "समस्या का दावा करें",
    claimedBadge: "परिसर द्वारा दावा किया गया",
    pendingProposals: "CSR प्रतीक्षित प्रस्ताव",
    activeProjectsCount: "सक्रिय इंजीनियरिंग पायलट",
    assignedQueueTitle: "आने वाली परिसर समस्या कतार",

    // Industry Pages
    industryQueueTitle: "उद्योग CSR सामाजिक नवाचार कतार",
    industryQueueSubtitle: "विश्वविद्यालय शोध प्रस्तावों की समीक्षा करें, बजट माइलस्टोन का मूल्यांकन करें और सीएसआर अनुदान आवंटित करें।",
    sponsorProposalBtn: "प्रस्ताव प्रायोजित करें व अनुदान दें",
    fundingAllocated: "कुल आवंटित CSR अनुदान",
    fundedProjectsTitle: "उद्योग प्रायोजित परियोजनाएं",
    fundedProjectsSubtitle: "स्वीकृत शोध परियोजनाओं के माइलस्टोन, समयसीमा और सामाजिक प्रभाव की निगरानी करें।",

    // Admin Pages
    adminDashboardTitle: "राज्य स्तरीय नवाचार कमांड सेंटर",
    adminDashboardSubtitle: "समस्या रूटिंग, विश्वविद्यालय सहभागिता, सीएसआर अनुदान और समाधान गति की रीयल-टाइम निगरानी।",
    verifyAccountsTitle: "संस्थान एवं उपयोगकर्ता सत्यापन",
    verifyAccountsSubtitle: "विश्वविद्यालयों और सीएसआर कंपनियों के दस्तावेजों की जांच करें और अनुमोदन प्रदान करें।",

    // Status Badges
    statusNew: "नई समस्या",
    statusUnderReview: "समीक्षाधीन",
    statusAssigned: "विश्वविद्यालय आवंटित",
    statusInProgress: "प्रगति पर",
    statusFunded: "अनुदान स्वीकृत",
    statusResolved: "हल व सत्यापित",
    priorityHigh: "उच्च प्राथमिकता",
    priorityMedium: "मध्यम प्राथमिकता",
    priorityLow: "सामान्य प्राथमिकता",
  },

  // Jharkhand Regional Language: Khortha (खोरठा)
  kht: {
    // TopBar & Header
    searchPlaceholder: "समस्या, शोध प्रोजेक्ट, यूनिवर्सिटी, सीएसआर साथी खोजा...",
    liveNotifications: "ताज़ा सूचना सब",
    markAllRead: "सभे पढ़ल चिह्नित करा",
    noNotifications: "कौनों नया सूचना नय हे।",
    viewProgressTracker: "चाल-चलन ट्रैकर देखा →",
    signOut: "लॉग आउट करा",
    language: "भाषा",
    signedInAs: "लॉग इन करल नाम",
    role: "भूमिका",
    organization: "संस्थान / कंपनी",
    district: "जिला",

    // Roles
    citizen: "नागरिक / जनता",
    university: "विश्वविद्यालय / कॉलेज",
    industry: "उद्योग / CSR साथी",
    admin: "सरकार / एडमिन",

    // Navigation & Sidebar
    portalBrand: "सहयोग",
    portalSubtitle: "सामाजिक नवाचार पोर्टल",
    navReportIssue: "समस्या दर्ज करा",
    navMyIssues: "हामर समस्या सब",
    navCampusQueue: "यूनिवर्सिटी कतार",
    navProjects: "शोध प्रोजेक्ट",
    navCsrQueue: "CSR अनुदान प्रस्ताव",
    navFundedProjects: "स्वीकृत प्रोजेक्ट सब",
    navAdminAnalytics: "राज्य भरक विश्लेषण",
    navVerifyAccounts: "खाता जांच",
    networkOverview: "सहयोग नेटवर्क",
    networkActive: "सक्रिय",

    // Landing Page
    heroBadge: "AI-चलवइया सामाजिक नवाचार मंच",
    heroTitlePre: "झारखंडक नागरिक समस्या के जोड़ना ",
    heroTitleHighlight: "यूनिवर्सिटी आरु उद्योग साथी से",
    heroSubtitle: "नागरिक फोटो आरु थोड़का बात लिख के समस्या दर्ज करथीन। हमर AI इंजन समस्या के जांच के नजदीकी यूनिवर्सिटी सब के भेज देहे, जहां प्रोफेसर-छात्र मिल के CSR अनुदान से समाधान बनावथीन।",
    reportCivicBtn: "समस्या दर्ज करा",
    loginBtn: "यूनिवर्सिटी / उद्योग लॉगिन",
    signIn: "लॉगिन करा",
    joinNetwork: "नेटवर्क में जुड़ा",
    heroCheck1: "AI समस्या सूत्रीकरण",
    heroCheck2: "नजदीकी यूनिवर्सिटी रूटिंग",
    heroCheck3: "जनता के तुरंत खबर",
    liveActivity: "मंचक लाइव गतिविधि",
    liveActivitySample: "टाटा स्टील CSR लेल फ्लोराइड शुद्धिकरण पायलट",
    liveActivitySampleSub: "बीआईटी मेसरा के मिलल · निकटतम कैंपस (12.4 किमी) · 60 दिनक समय",
    howItWorks: "सहयोग कइसे काम करहे",
    fromReportToResolution: "समस्या दर्ज से ले के जमीन पर समाधान तक",
    workflowStep1Title: "1. नागरिक रिपोर्टिंग",
    workflowStep1Desc: "नागरिक फोटो आरु स्थान के साथे अपन गांव/मुहल्लाक समस्या दर्ज करथीन।",
    workflowStep2Title: "2. AI जांच आरु रूटिंग",
    workflowStep2Desc: "AI समस्याक गंभीरता जांचे हे आरु नजदीकी यूनिवर्सिटी के सीधे भेज देहे।",
    workflowStep3Title: "3. यूनिवर्सिटी समाधान",
    workflowStep3Desc: "प्रोफेसर आरु छात्र मिल के इंजीनियरिंग प्रोटोटाइप आरु समाधान बनावथीन।",
    workflowStep4Title: "4. उद्योग CSR अनुदान आरु समाधान",
    workflowStep4Desc: "उद्योग साथी पैसा देके प्रोजेक्ट पूरा करावथीन आरु जनता के खबर मिल जाय हे।",
    platformImpactDashboard: "झारखंड प्रभाव डैशबोर्ड",
    realtimeIndicators: "सभे जिला के रीयल-टाइम आंकड़े",
    viewFullAnalytics: "पूरा विश्लेषण देखा →",
    copyrightFooter: "© 2026 सहयोग — सामाजिक नवाचार सहभागिता मंच। सभे अधिकार सुरक्षित।",
    collabCivicSolving: "मिल-जुल के समस्या समाधान",

    // Auth (Login & Signup)
    welcomeBack: "सहयोग में तोहर स्वागत हे",
    signInWorkspace: "अपन सहभागिता डैशबोर्ड में लॉगिन करा।",
    continueGoogle: "Google से आगे बढ़ा",
    continueCredentials: "या ईमेल आरु पासवर्ड से लॉगिन करा",
    quickDemoSwitcher: "डेमो खाता चुनवा:",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    signInToDashboard: "डैशबोर्ड में घुसा",
    signingIn: "लॉगिन भेल लागल हे...",
    newToSahayog: "सहयोग में नया हका?",
    createAnAccount: "नया खाता बनावा",
    alreadyHaveAccount: "पहिले से खाता हे?",
    joinSahayogNetwork: "सहयोग नेटवर्क में जुड़ा",
    fullName: "पूरा नाम",
    selectRole: "अपन भूमिका चुना",
    institutionName: "यूनिवर्सिटी / कंपनी के नाम",
    department: "विभाग / CSR शाखा",

    // Report Issue Wizard
    reportTitle: "नागरिक समस्या दर्ज करा",
    reportSubtitle: "फोटो आरु थोड़का विवरण दा। हमर AI इंजन शोध विवरण बना के नजदीकी यूनिवर्सिटी के भेजतो।",
    stepBasic: "मूल जानकारी",
    stepDesc: "समस्याक विवरण",
    stepPhoto: "फोटो प्रमाण",
    stepLocation: "जगह / स्थान",
    stepReview: "AI जांच आरु समीक्षा",
    issueTitleLabel: "समस्याक शीर्षक",
    issueTitlePlaceholder: "उदा. अल्बर्ट एक्का चौक पर नाली जाम आरु पानी भराव",
    categoryLabel: "समस्याक श्रेणी",
    selectCategory: "श्रेणी चुना",
    descLabel: "समस्याक संक्षिप्त विवरण",
    descPlaceholder: "उदा. बरसात में नाली सड़क पर बहे लागल हे, 300 मीटर तक रास्ता बंद हे...",
    descTip: "सुझाव: विवरण छोट राखा! ककरा परेशानी हे आरु कतेक दिन से हे, सेकर उल्लेख करा। सहयोग AI मॉडल यूनिवर्सिटी लेल फॉर्मल समस्या विवरण तैयार करतो।",
    photoLabel: "फोटो / प्रमाण अपलोड करा",
    photoSubtitle: "फोटो से AI बाढ़ खतरा आरु जरूरी स्कोर जांचे हे।",
    districtLabel: "जिला (झारखंड)",
    blockLabel: "प्रखंड / निकाय",
    blockPlaceholder: "उदा. कांके / तमाड़ / जमशेदपुर",
    landmarkLabel: "सड़क / लैंडमार्क",
    landmarkPlaceholder: "उदा. अल्बर्ट एक्का चौक लगे",
    pinLocationMap: "नक्शा पर सही जगह चुना (यूनिवर्सिटी दूरी लेल)",
    useGps: "अखनक GPS स्थान लेवा",
    aiSynthesizing: "AI शोध विवरण तैयार भेल लागल हे...",
    aiFormulatedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या आरु गंभीरता",
    regenerateAi: "फेरु से AI बनावा",
    publicRisk: "जनताक जोखिम",
    floodRisk: "बाढ़ जोखिम",
    urgencyLevel: "तात्कालिकता",
    compositeScore: "कुल गंभीरता स्कोर",
    backBtn: "पाछे",
    continueBtn: "आगे बढ़ा",
    submitBtn: "नजदीकी यूनिवर्सिटी सब के भेजो",
    submittingBtn: "सहयोग नेटवर्क पर प्रकाशित भेल लागल हे...",

    // My Reported Challenges
    myReportedChallenges: "हामर दर्ज करल समस्या सब",
    myReportedSubtitle: "समस्या मूल्यांकन, यूनिवर्सिटी टीम, उद्योग अनुदान आरु समाधान माइलस्टोन के देखा।",
    reportNewChallenge: "नया समस्या दर्ज करा",
    noReportedIssues: "तोहें अभी तक कौनों समस्या दर्ज नय करले ह।",
    noReportedHelper: "AI जांच शुरू करे लेल आरु नजदीकी यूनिवर्सिटी तक पहुंचावे लेल अपन जिलाक समस्या फोटो सहित दर्ज करा।",

    // Issue Detail
    citizenDescription: "नागरिक द्वारा देल विवरण",
    aiSynthesizedTitle: "AI-द्वारा तैयार औपचारिक शोध समस्या",
    evidencePhotos: "फोटो प्रमाण व अपलोड",
    nearestRoutingTitle: "नजदीकी यूनिवर्सिटी आरु दूरी रूटिंग",
    assembleTeamTitle: "बहुविषयक टीम बनावा",
    assembleTeamSubtitle: "समाधान प्रस्ताव बनावे लेल अलग-अलग विभागक छात्र आरु प्रोफेसर के टीम बनावा।",
    saveTeamDraftProposal: "टीम सुरक्षित करा आरु प्रस्ताव बनावा",
    exportCsrCert: "CSR इम्पैक्ट प्रमाणपत्र",
    claimChallenge: "यूनिवर्सिटी लेल दावा करा",
    claiming: "दावा दर्ज भेल लागल हे...",
    nearestCampus: "सबले नियरे कैंपस",
    kmFromCampus: "किमी दूर कैंपस से",
    priority1: "प्राथमिकता 1",
    priority2: "प्राथमिकता 2",

    // Progress Tracker
    trackerTitle: "लाइव समस्या चाल-चलन ट्रैकर",
    trackerSubtitle: "नागरिक समस्या समाधान लेल रीयल-टाइम अमेज़न-स्टाइल डिलीवरी ट्रैकर",
    stageReported: "दर्ज व AI जांचल",
    stageAssigned: "यूनिवर्सिटी टीम बनल",
    stageFunded: "प्रस्ताव व CSR अनुदान पास",
    stageExecution: "मैदान में काम व माइलस्टोन",
    stageResolved: "समाधान संपन्न व जांचल",
    stageCompleted: "पूरा भेल",
    stageInProgress: "काम चल रहल हे",
    stageUpcoming: "आगे अइतो",
    liveActivityFeed: "लाइव गतिविधि व माइलस्टोन ऑडिट फ़ीड",
    overallResolution: "कुल समाधान प्रगति",

    // Citizen Feedback & Verification
    feedbackTitle: "नागरिक समाधान जांच आरु रेटिंग",
    feedbackSubtitle: "जमीन पर काम भेल हे कि नय, सेकर पुष्टि करा आरु यूनिवर्सिटी टीम के रेट करा।",
    rateSolution: "समाधान के गति आरु काम के स्टार दा:",
    feedbackPlaceholder: "समुदाय आरु राज्य परिषद के जमीनी प्रभाव बतावा (उदा. पानी अखन पूरा साफ आरु चालू हे!)...",
    verifyGroundCheck: "हम पुष्टि करहियो कि ई नागरिक समस्या जमीन पर पूरा हल भेल हे।",
    submitFeedbackBtn: "जांच आरु रेटिंग जमा करा",
    verifiedByCitizenBadge: "नागरिक द्वारा जांचल",
    citizenRatingLabel: "नागरिक संतुष्टि स्कोर",
    thankYouFeedback: "जांच आरु रेटिंग देवे लेल धन्यवाद!",

    // University Pages
    uniDashboardTitle: "विश्वविद्यालय अनुसंधान एवं नवाचार केंद्र",
    uniDashboardSubtitle: "स्थानीय समस्याक जांच करा, छात्र-प्रोफेसरक बहुविषयक टीम बनावा आरु शोध प्रस्ताव तैयार करा।",
    claimBtn: "समस्या पर दावा करा",
    claimedBadge: "कैंपस द्वारा दावा करल",
    pendingProposals: "CSR प्रतीक्षित प्रस्ताव",
    activeProjectsCount: "चालू इंजीनियरिंग पायलट",
    assignedQueueTitle: "आवे वाला कैंपस समस्या कतार",

    // Industry Pages
    industryQueueTitle: "उद्योग CSR सामाजिक नवाचार कतार",
    industryQueueSubtitle: "यूनिवर्सिटी शोध प्रस्ताव के देखा, बजट माइलस्टोन जाँचा आरु CSR अनुदान पास करा।",
    sponsorProposalBtn: "प्रस्ताव स्पॉन्सर करा व पैसा दा",
    fundingAllocated: "कुल देल CSR अनुदान",
    fundedProjectsTitle: "उद्योग संपोषित प्रोजेक्ट सब",
    fundedProjectsSubtitle: "स्वीकृत शोध प्रोजेक्ट के माइलस्टोन, समय आरु सामाजिक प्रभाव के देखा।",

    // Admin Pages
    adminDashboardTitle: "राज्य भरक नवाचार कमांड सेंटर",
    adminDashboardSubtitle: "समस्या रूटिंग, यूनिवर्सिटी भागीदारी, CSR अनुदान आरु समाधान गतिक रीयल-टाइम निगरानी।",
    verifyAccountsTitle: "संस्थान आरु यूजर जांच",
    verifyAccountsSubtitle: "यूनिवर्सिटी आरु CSR कंपनी सब के कागजात जाँचा आरु मंजूरी दा।",

    // Status Badges
    statusNew: "नया समस्या",
    statusUnderReview: "जांच चल रहल हे",
    statusAssigned: "यूनिवर्सिटी मिलल",
    statusInProgress: "काम चल रहल हे",
    statusFunded: "अनुदान पास भेल",
    statusResolved: "हल भेल व जांचल",
    priorityHigh: "भारी जरूरी",
    priorityMedium: "मध्यम जरूरी",
    priorityLow: "साधारण",
  },
};

export const useLanguageStore = create((set, get) => ({
  language: localStorage.getItem("sahayog_lang") || "en",
  setLanguage: (lang) => {
    localStorage.setItem("sahayog_lang", lang);
    set({ language: lang });
  },
  t: (key) => {
    const lang = get().language;
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
  },
}));
